/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Smartphone_sales_management.UI.Component.DonHangComponent;

import Smartphone_sales_management.DTO.Model_DonHang;
import java.awt.print.PrinterException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.jfree.data.time.Day;

/**
 *
 * @author Admin
 */
public class PanelInHoaDon extends javax.swing.JPanel {

    /**
     * Creates new form PanelInHoaDon
     */
    ArrayList dsct;
    String Madonhang;
    String dulieudonhang = "";
    int i = 1;
    int total = 0;
    String tongtien = "";
    String tenkhachhang = "";
    String ngaybandonhang = "";
    JFrame frame;
    //y.get(1).toString() teen san pham
    //y.get(3).toString() so luong
    // y.get(10).toString() gia
    //y.get(7).toString() gia sau km
    // y.get(6).toString() tong gia

    public PanelInHoaDon(ArrayList dsct, JFrame frame) {
        initComponents();
        this.frame = frame;
        this.dsct = dsct;
        for (Object x : dsct) {
            Vector y = (Vector) x;
            String Madh = y.get(0).toString();
            Madonhang = Madh;
            String stt = "STT\t" + String.valueOf(i) + "\n";
            i++;
            String tenSp = "Tên sản phẩm \t\t\t" + y.get(1).toString() + "\n";
            String soluong = "Số lượng: \t\t\t" + y.get(3).toString() + "\n";
            String gia = "Giá: \t\t\t" + y.get(10).toString() + "\n";
            String giaSauKM = "Giá sau khuyến mãi: \t\t" + y.get(7).toString() + "\n";
            int TongGia = Integer.parseInt(y.get(7).toString()) * Integer.parseInt(y.get(3).toString());
            String tongGia = "Sub Total :\t\t\t" + String.valueOf(TongGia) + "\n";
            int subtotal = Integer.parseInt(String.valueOf(TongGia));
            String underline = "\t\t=====================================\n";
            String data = stt + tenSp + soluong + gia + giaSauKM + tongGia + underline;
            dulieudonhang += data;
            total += subtotal;
            String tong = String.valueOf(total);
            String tenKH = y.get(11).toString();
            Date ngayBan = (Date) y.get(12);
            ngaybandonhang = ngayBan.toString();
            tongtien = tong;
            tenkhachhang = tenKH;
        };
        textReceipt.append("\t\t\t Hóa đơn \t" + Madonhang
                + "\n Tên Khách Hàng: \t" + tenkhachhang
                + "\n Ngày bán: \t\t" + ngaybandonhang
                + "\n\n=============================================================================================\n"
                + dulieudonhang + "\n"
                + "Tổng tiền\t\t\t" + tongtien + "VND"
                + "\n\n\n\t\t==============  Cảm ơn quý khách! =============="
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textReceipt = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("In Hóa Đơn");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(273, 273, 273))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        textReceipt.setColumns(20);
        textReceipt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        textReceipt.setRows(5);
        jScrollPane2.setViewportView(textReceipt);

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/print.png"))); // NOI18N
        jButton1.setText("In Hóa đơn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/back-icon.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Bạn muốn in hóa đơn ?", "In hóa đơns ", JOptionPane.YES_NO_OPTION);
        if (JOptionPane.YES_OPTION == a) {
            try {
                textReceipt.print();
            } catch (PrinterException ex) {
                Logger.getLogger(PanelInHoaDon.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Bạn muốn thoát ?", "Thoát ", JOptionPane.YES_NO_OPTION);
        if (a == JOptionPane.YES_OPTION) {
            frame.dispose();
        }
    }//GEN-LAST:event_btnExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea textReceipt;
    // End of variables declaration//GEN-END:variables
}
