/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Smartphone_sales_management.UI.Component.TaiKhoan2;

import Smartphone_sales_management.UI.Component.TaiKhoanComponent.*;
import Smartphone_sales_management.BUS.QuanLyTaiKhoan_BUS;
import Smartphone_sales_management.DAO.QuanLyTaiKhoan_DAO;
import Smartphone_sales_management.UI.Component.BanHangComponent.AddKhachHang;
import Smartphone_sales_management.UI.Event.TaiKhoan.EventTaiKhoan;
import Smartphone_sales_management.UI.Main.MainFrame;
import java.awt.GridLayout;
import Smartphone_sales_management.UI.Event.TaiKhoan.AddDetailTK;
import Smartphone_sales_management.UI.Event.TaiKhoan.LayMatk;
import Smartphone_sales_management.UI.Model.Model_TaiKhoan;
import Smartphone_sales_management.UI.Swing.GraphicsTextFied;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.Font;
import java.awt.Window;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;
import javax.swing.text.TabableView;

/**
 *
 * @author Windows10
 */
public class MainConTentTaiKhoan2 extends javax.swing.JPanel {

    EventTaiKhoan event;
    MainFrame frame;
    QuanLyTaiKhoan_BUS qltk = new QuanLyTaiKhoan_BUS();
    QuanLyTaiKhoan_DAO a = new QuanLyTaiKhoan_DAO();
    ArrayList data = new ArrayList();
    DefaultTableModel model = new DefaultTableModel();
    int Matk = -1;
    ArrayList dataChitietTK = null;

    public MainConTentTaiKhoan2(MainFrame frame) {
        initComponents();
        this.frame = frame;
        model.addColumn("Mã Tài Khoản");
        model.addColumn("Mã Nhân Viên");
        model.addColumn("Tên Nhân Viên");
        model.addColumn("Tên Đăng Nhập");
        model.addColumn("Mật khẩu");
        TableTaiKhoan.setOpaque(false);
        TableTaiKhoan.getTableHeader().getColumnModel().setColumnMargin(1);
        TableTaiKhoan.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 17) {
        });
        TableTaiKhoan.getTableHeader().setForeground(Color.WHITE);
        TableTaiKhoan.getTableHeader().setBackground(new Color(14, 14, 14));
        TableTaiKhoan.setModel(model);
        addEventTaiKhoan(new EventTaiKhoan() {
            @Override
            public int SelectedInxex(int index) {
                Matk = index;
                return -1;
            }
        ;
        });
        setDefautlTaiKhoan();

//        DetailTaiKhoanPanel.add(tbdtTK);
        timkiem.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) {

                setDefautlTaiKhoan();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                setDefautlTaiKhoan();

            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                setDefautlTaiKhoan();

            }
        });

    }

    public void addEventTaiKhoan(EventTaiKhoan event) {
        TableTaiKhoan.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
//                event.selectedIndex(jTable1.getSelectedRow());
                Matk=(int) TableTaiKhoan.getValueAt(TableTaiKhoan.getSelectedRow(), 0);

            }

        }
        );

    }

    public void setDefautlTaiKhoan() {
        TableTaiKhoan.removeAll();
        model.setRowCount(0);
        ArrayList dataList = new ArrayList<>();
        dataList = qltk.layDanhSachTaiKhoan2(timkiem.getText());
        for (int i = 0; i < dataList.size(); i++) {
            model.addRow((Vector<?>) dataList.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        javax.swing.JPanel Nền = new javax.swing.JPanel();
        timkiem = new GraphicsTextFied(20);
        jScrollPane2 = new javax.swing.JScrollPane();
        TableTaiKhoan = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSuaTaiKhoan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/search.png"))); // NOI18N

        Nền.setBackground(new java.awt.Color(255, 255, 255));

        timkiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiemActionPerformed(evt);
            }
        });

        TableTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TableTaiKhoan.setRowHeight(35);
        TableTaiKhoan.setSelectionBackground(new java.awt.Color(204, 0, 0));
        TableTaiKhoan.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(TableTaiKhoan);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/search.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Tài Khoản");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Quản Lý Quyền TK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(0, 0, 0));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm tài khoản");
        btnThem.setBorder(null);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSuaTaiKhoan.setBackground(new java.awt.Color(0, 0, 0));
        btnSuaTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSuaTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaTaiKhoan.setText("Sữa Tài Khoản");
        btnSuaTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaTaiKhoanActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Xóa Tài Khoản");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NềnLayout = new javax.swing.GroupLayout(Nền);
        Nền.setLayout(NềnLayout);
        NềnLayout.setHorizontalGroup(
            NềnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NềnLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(NềnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(NềnLayout.createSequentialGroup()
                        .addGroup(NềnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(NềnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(NềnLayout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSuaTaiKhoan)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1))))
                .addGap(26, 26, 26))
        );
        NềnLayout.setVerticalGroup(
            NềnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NềnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NềnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NềnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(NềnLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel4)
                .addContainerGap(328, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Nền, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nền, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
      public void DisPlayComponent(Component taikhoan) {

    }
    private void timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timkiemActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        JDialog inforDonHang = new JDialog();
//        changePwdDialog.setUndecorated(true);
//          ThongTinDonHang donhang = new ThongTinDonHang(data,this,inforDonHang);
        TableAddTaiKhoan2 themtaikhoan = new TableAddTaiKhoan2(MainConTentTaiKhoan2.this, inforDonHang);
        inforDonHang.setSize(580, 340);
        inforDonHang.setLayout(new GridLayout());
        inforDonHang.setTitle("Thêm khách hàng");
        inforDonHang.add(themtaikhoan);
        themtaikhoan.validate();
        inforDonHang.setLocationRelativeTo(null);
        inforDonHang.setVisible(true);

        
        
        
//        JFrame frame = new JFrame("Them tai khoan");
//        TableAddTaiKhoan2 themTaiKhoan = new TableAddTaiKhoan2();
//        frame.setSize(567, 383);
//        frame.setLocationRelativeTo(null);
//        frame.add(themTaiKhoan);
//        frame.setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed
    public boolean checkMatk(int Matk) {
        if (Matk != -1) {
            return true;
        }
        return false;
    }

    private boolean checkMatk() {
        if (Matk != -1) {
            return true;
        }
        return false;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrame frame = new JFrame("Bản phân quyền tài khoản");
        FromQuyen2 quyen = new FromQuyen2();
        frame.setSize(800, 600);
        frame.setLocationRelativeTo(null);
        frame.add(quyen);
        frame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSuaTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaTaiKhoanActionPerformed

        int a = JOptionPane.showConfirmDialog(null, "Bạn muốn sửa ?", "Sửa sản phẩm ", JOptionPane.YES_NO_OPTION);
        if (a == JOptionPane.YES_OPTION) {
            if (checkMatk()) {
                ArrayList data = new ArrayList();
                data = qltk.layDanhSachChiTietTai(Matk);
                JFrame frame = new JFrame("Them thong tin");
                TableUpdateTaiKhoan2 suaTaiKhoan = new TableUpdateTaiKhoan2(data, frame, TableTaiKhoan, this.frame);
                frame.setSize(567, 383);
                frame.setLocationRelativeTo(null);
                frame.add(suaTaiKhoan);
                frame.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Chưa chọn sản phẩm để sửa !");
            }

        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnSuaTaiKhoanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int a = JOptionPane.showConfirmDialog(null, "Bạn muốn xóa ?", "Xóa tài khoản ", JOptionPane.YES_NO_OPTION);
        if (a == JOptionPane.YES_OPTION) {
            if (checkMatk(Matk)) {
                QuanLyTaiKhoan_BUS qltk_BUS = new QuanLyTaiKhoan_BUS();
                if (qltk_BUS.xoaTK(Matk)) {
                    JOptionPane.showMessageDialog(null, "Xóa thành công");
                    setDefautlTaiKhoan();
                    Matk = -1;
                } else {
                    JOptionPane.showMessageDialog(null, "Xóa thất bại!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Chưa chọn tài khoản muốn xóa");
            }
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableTaiKhoan;
    private javax.swing.JButton btnSuaTaiKhoan;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField timkiem;
    // End of variables declaration//GEN-END:variables
}
