/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Smartphone_sales_management.UI.Component.ThongKeBaoCaoComponent;

import Smartphone_sales_management.BUS.QuanLyBanHang_BUS;
import Smartphone_sales_management.BUS.ThongKeBaoCao_BUS;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vuong
 */
public class TableBanHang_TheoHangHoa extends javax.swing.JPanel {

    /**
     * Creates new form TableBanHang_TheoHangHoa
     */
    ThongKeBaoCao_BUS tkbc = new ThongKeBaoCao_BUS();

    DefaultTableModel model = new DefaultTableModel();
    private String type;
    private String hinhthuc;
    private Date datetart;
    private Date dateEnd;

    public TableBanHang_TheoHangHoa(String type, String hinhthuc, Date dateStart, Date dateEnd) {
        initComponents();
        this.type = type;
        this.hinhthuc = hinhthuc;
        this.dateEnd = dateEnd;
        this.datetart = dateStart;

        SetDefautlTable();
        jTable1.setModel(model);
    }

    public void SetDefautlTable() {
        jTable1.removeAll();
        model.setRowCount(0);
        if (hinhthuc.equals("Hàng Hóa")) {
            this.model.addColumn("STT");
            model.addColumn("Mã Hàng");
            model.addColumn("Tên Hàng");
            model.addColumn("Số Lượng");
//            model.addColumn("Số Lượng còn");

        } 
         if (hinhthuc.equals("Ngày Bán")) {
            this.model.addColumn("STT");
            model.addColumn("Mã Hàng");
            model.addColumn("Tên Hàng");
            model.addColumn("Số Lượng");
             System.out.println(dateEnd.toString());
             System.out.println(datetart.toString());
             System.out.println(datetart.compareTo(dateEnd));

//            model.addColumn("Số Lượng còn");

        } 
        if(hinhthuc.equals("Khách Hàng")) {
            this.model.addColumn("STT");
            model.addColumn("Mã Khách Hàng");
            model.addColumn("Tên Khách Hàng");
            model.addColumn("Số Đơn");
            model.addColumn("Số Lượng");
            model.addColumn("Tồng tiền");

        }
        jTable1.setOpaque(false);
        jTable1.getTableHeader().getColumnModel().setColumnMargin(1);
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 17) {
        });
        jTable1.getTableHeader().setForeground(Color.WHITE);
        jTable1.getTableHeader().setBackground(new Color(14, 14, 14));
//        jTable1.s  (jTable1.getWidth(), new double[]{0.5, 1, 1, 1, 2, 1, 2, 2, 2});
        if(datetart==null || dateEnd==null)
        {
                    ArrayList dataList = new ArrayList<>();
        dataList =tkbc.getThongKeBaoCaoBanHang(type,hinhthuc);
//            System.out.println(hinhthuc);
        for (int i = 0; i < dataList.size(); i++) {
            model.addRow((Vector<?>) dataList.get(i));
        }
        }
        jScrollPane1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(255, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private ArrayList getThongKeBaoCaoBanHang(String type, String hinhthuc) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
