/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Smartphone_sales_management.UI.Component.ThongKeBaoCaoComponent;

import Smartphone_sales_management.BUS.LoiNhuanBanHang_BUS;
import Smartphone_sales_management.BUS.ThongKeBaoCaoBanHang_BUS;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vuong
 */
public class TableLoiNhuanBanHang extends javax.swing.JPanel {

    /**
     * Creates new form TableBanHang_TheoKhachHang
     */
    LoiNhuanBanHang_BUS lnbh = new LoiNhuanBanHang_BUS();

    DefaultTableModel model;
    private String type;
    private String hinhthuc;
    private Date datetart;
    private Date dateEnd;

    public TableLoiNhuanBanHang(String type, String hinhthuc) {
        initComponents();
        this.type = type;
        this.hinhthuc = hinhthuc;
        jTable1.setOpaque(false);
        jTable1.getTableHeader().getColumnModel().setColumnMargin(1);
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 17) {
        });
        jTable1.getTableHeader().setForeground(Color.WHITE);
        jTable1.getTableHeader().setBackground(new Color(14, 14, 14));
    }

    public TableLoiNhuanBanHang(String type, String hinhthuc, Date dateStart, Date dateEnd) {
        initComponents();
        this.type = type;
        this.hinhthuc = hinhthuc;
        this.dateEnd = dateEnd;
        this.datetart = dateStart;
        jTable1.setOpaque(false);
        jTable1.getTableHeader().getColumnModel().setColumnMargin(1);
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 17) {
        });
        jTable1.getTableHeader().setForeground(Color.WHITE);
        jTable1.getTableHeader().setBackground(new Color(14, 14, 14));
        SetDefautlTable();
    }

    public void init(String type, String hinhthuc, Date dateStart, Date dateEnd) {
        this.type = type;
        this.hinhthuc = hinhthuc;
        this.dateEnd = dateEnd;
        this.datetart = dateStart;
        SetDefautlTable();

    }

    public void init(String type, String hinhthuc) {
        this.type = type;
        this.hinhthuc = hinhthuc;
        SetDefautlTable();

    }

    public void SetDefautlTable() {

        jTable1.removeAll();
        model = new DefaultTableModel();
        model.setRowCount(0);
        if (hinhthuc.equals("Hàng Hóa")) {
            this.model.addColumn("STT");
            model.addColumn("Mã Hàng");
            model.addColumn("Tên Hàng");
            model.addColumn("Tổng Số Bán Ra");
            model.addColumn("Thành Tiền");
            model.addColumn("Tiền Sau KM");
            model.addColumn("Tiền Vốn");
            model.addColumn("Tiền Lãi");
        }
        if (hinhthuc.equals("Ngày Bán")) {
            model.addColumn("STT");
            model.addColumn("Ngày Bán");
            model.addColumn("Số Lượng Đơn Bán Ra");
            model.addColumn("Số Lượng Bán Ra");
            model.addColumn("Tổng Tiền");
            model.addColumn("Tiền Vốn");
            model.addColumn("Tiền Lãi");
        }
        jTable1.setOpaque(false);
        jTable1.getTableHeader().getColumnModel().setColumnMargin(1);
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 17) {
        });
        jTable1.getTableHeader().setForeground(Color.WHITE);
        jTable1.getTableHeader().setBackground(new Color(14, 14, 14));

        ArrayList dataList = new ArrayList<>();
        if (hinhthuc.equals("Hàng Hóa")) {
            dataList = lnbh.getLoiNhuanBanHang_HangHoa();
        }
        if (hinhthuc.equals("Ngày Bán")) {
            dataList = lnbh.getLoiNhuanBanHang_NgayBan(datetart, dateEnd);
        }
        for (int i = 0; i < dataList.size(); i++) {
            model.addRow((Vector<?>) dataList.get(i));
        }
        jTable1.setModel(model);
        jScrollPane1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    JTable getTable() {
        return jTable1;
    }
}
