/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Smartphone_sales_management.UI.Component.PhieuNhap;

import Smartphone_sales_management.BUS.QuanLyPhieuNhap_BUS;
import Smartphone_sales_management.UI.Main.MainFrame;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vuong
 */
public class TableChiTietPhieuNhap extends javax.swing.JPanel {

    /**
     * Creates new form TableChiTietPhieuNhap
     */
    QuanLyPhieuNhap_BUS qlpn = new QuanLyPhieuNhap_BUS();
    MainFrame frame;
    private int Mapn;
    private String ngaynhap;
    private String tenncc;
    DefaultTableModel model = new DefaultTableModel();

    public TableChiTietPhieuNhap(int Maph,String Ngaynhap,String tenncc ,MainFrame frame) {
        initComponents();
        this.frame = frame;
        this.ngaynhap=Ngaynhap;
        this.tenncc=tenncc;
        Mapn=Maph;
        this.tenncc=tenncc;
        
        model.addColumn("STT");
        model.addColumn("Mã Sản Phẩm");
        model.addColumn("Tên Sản Phẩm");
        model.addColumn("Giá Nhập");
        model.addColumn("Số Lượng");
        model.addColumn("Tổng Tiền");
        jTable1.setOpaque(false);
        jTable1.getTableHeader().getColumnModel().setColumnMargin(1);
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 17) {
        });
        jTable1.getTableHeader().setForeground(Color.WHITE);
        jTable1.getTableHeader().setBackground(new Color(14, 14, 14));
        jTable1.setModel(model);
        DisplayDetailPhieuNhap();
    }

    private void DisplayDetailPhieuNhap() {
//        
        ArrayList data = new ArrayList();
        data = qlpn.getChiTietPhieuNhap(Mapn);
         jTable1.removeAll();
        model.setRowCount(0);
        for (int i = 0; i < data.size(); i++) {
            model.addRow((Vector<?>) data.get(i));
        }
        jScrollPane1.repaint();
        lbMaPhieuNhap.setText(Integer.toString(Mapn));
        lbNgayNhap.setText(ngaynhap);
        lbNhaCungCap.setText(tenncc);
   
        
//        Model_BanHang_ChiTietSanPham model = data.get(0);
//        lbcName.setText(model.getTensp());
//        lbcLoai.setText(model.getLoaisp());
//        String km = String.valueOf(model.getPtkm()) + " %";
//        lbnKhuyenMai.setText(km);
//        lbnBaoHanh.setText(model.getBaohanh());
//        String SL = String.valueOf(model.getSl());
//        lbcSL.setText(SL);
//        lbcNamSx.setText(model.getNamsx());
//        lbcNCC.setText(model.getTenncc());
//        String gia = String.valueOf(model.getGiaban());
//        lbcGia.setText(gia + " VND");
//        this.urlImage = model.getIcon();
//        String str = model.getChitiet();
//        String[] tachChuoi = str.split("//");
//        String chuoiChinh = "";
//        for (String string : tachChuoi) {
//            chuoiChinh += (string + "\n");
//        }
//       
//        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbNhaCungCap = new javax.swing.JLabel();
        lbNgayNhap = new javax.swing.JLabel();
        lbMaPhieuNhap = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Mã Phiếu Nhập: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Ngày Nhập: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Tên Nhà Cung Cấp:");

        lbNhaCungCap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNhaCungCap.setForeground(new java.awt.Color(204, 0, 0));
        lbNhaCungCap.setText("lbTenNhaCungCap");

        lbNgayNhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNgayNhap.setForeground(new java.awt.Color(204, 0, 0));
        lbNgayNhap.setText("jLabel4");

        lbMaPhieuNhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbMaPhieuNhap.setForeground(new java.awt.Color(204, 0, 0));
        lbMaPhieuNhap.setText("lbMaPhieuNhap");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(30);
        jTable1.setRowMargin(10);
        jTable1.setSelectionBackground(new java.awt.Color(255, 0, 0));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Thông Tin Phiếu Nhập");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMaPhieuNhap)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbNhaCungCap)
                                        .addGap(75, 75, 75)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbNgayNhap)))
                        .addGap(136, 136, 136)))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaPhieuNhap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbNhaCungCap)
                    .addComponent(jLabel3)
                    .addComponent(lbNgayNhap))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbMaPhieuNhap;
    private javax.swing.JLabel lbNgayNhap;
    private javax.swing.JLabel lbNhaCungCap;
    // End of variables declaration//GEN-END:variables
}
