/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Smartphone_sales_management.UI.Component;

import Smartphone_sales_management.UI.Event.EventBanHang;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.border.Border;
import Smartphone_sales_management.BUS.QuanLyBanHang_BUS;
import java.awt.FileDialog;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;


/**
 *
 * @author Vuong
 */
public class TableDetailBH extends javax.swing.JPanel {

    /**
     * Creates new form TableDetailBH
     */
    EventBanHang event ;
   public int indexSelected;
    public static int selectedIndex=-1;
    QuanLyBanHang_BUS qlbh_BUS = new QuanLyBanHang_BUS();
    public TableDetailBH(int index) {
        initComponents();
//        jButton1.setBackground(Color.WHITE);
     selectedIndex=index;
     if(selectedIndex!=-1)
     {
       DisplayInfor();
    }
    }

    
    
    public void DisplayInfor()
    {
       ArrayList data = new ArrayList();
       data = qlbh_BUS.getDanhSachChiTiet1SanPham(this.selectedIndex);
       lbcName.setText((String) data.get(0));
       lbcLoai.setText((String) data.get(1));
       lbcSL.setText(data.get(2).toString());
       lbcNamSx.setText((String) data.get(3));
       lbcNCC.setText((String) data.get(4));
       lbcGia.setText((String) data.get(5)+" VND");
       if(data.get(6)!=null)
       {
           
        lbImage.setIcon(new ImageIcon(getClass().getResource((String) data.get(6))));
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbName = new javax.swing.JLabel();
        lbLoai = new javax.swing.JLabel();
        lbSL = new javax.swing.JLabel();
        lbNamSx = new javax.swing.JLabel();
        lbNCC = new javax.swing.JLabel();
        lbGia = new javax.swing.JLabel();
        lbcName = new javax.swing.JLabel();
        lbcLoai = new javax.swing.JLabel();
        lbcSL = new javax.swing.JLabel();
        lbcNamSx = new javax.swing.JLabel();
        lbcNCC = new javax.swing.JLabel();
        lbcGia = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbImage = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(354, 450));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Xem chi tiết sản phẩm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jPanel3.setBackground(new java.awt.Color(255, 153, 102));

        lbName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbName.setText("Tên sản phẩm:");

        lbLoai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbLoai.setText("Loại sản phẩm:");

        lbSL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbSL.setText("Số lượng còn:");

        lbNamSx.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNamSx.setText("Năm sản xuất:");

        lbNCC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNCC.setText("Nhà cung cấp:");

        lbGia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbGia.setText("Giá Bán:         ");

        lbcName.setText("jLabel10");

        lbcLoai.setText("jLabel11");

        lbcSL.setText("jLabel12");

        lbcNamSx.setText("jLabel13");

        lbcNCC.setText("jLabel14");

        lbcGia.setText("jLabel15");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbLoai)
                        .addGap(10, 10, 10)
                        .addComponent(lbcLoai))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbSL)
                        .addGap(10, 10, 10)
                        .addComponent(lbcSL))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbNamSx)
                        .addGap(10, 10, 10)
                        .addComponent(lbcNamSx))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbName)
                        .addGap(10, 10, 10)
                        .addComponent(lbcName))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbGia)
                        .addGap(10, 10, 10)
                        .addComponent(lbcGia))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbNCC)
                        .addGap(10, 10, 10)
                        .addComponent(lbcNCC)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName)
                    .addComponent(lbcName))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLoai)
                    .addComponent(lbcLoai))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSL)
                    .addComponent(lbcSL))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNamSx)
                    .addComponent(lbcNamSx))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNCC)
                    .addComponent(lbcNCC))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGia)
                    .addComponent(lbcGia))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lbImage.setBackground(new java.awt.Color(204, 204, 255));
        lbImage.setText("jLabel9");

        btnThem.setText("Thêm ");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(205, 205, 205)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
//     
//            FileDialog fd = new FileDialog(new JFrame(), "Xuất excel", FileDialog.LOAD);
//        fd.setVisible(true);
//                String url = fd.getDirectory() + fd.getFile();
////                lbImage.setIcon(new ImageIcon(new URL(url)));
//              String[] url2= url.split("src");
//              String a = url2[1].replace("\\","/");
//              System.out.println(a);



// TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbGia;
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbLoai;
    private javax.swing.JLabel lbNCC;
    private javax.swing.JLabel lbNamSx;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbSL;
    private javax.swing.JLabel lbcGia;
    private javax.swing.JLabel lbcLoai;
    private javax.swing.JLabel lbcNCC;
    private javax.swing.JLabel lbcNamSx;
    private javax.swing.JLabel lbcName;
    private javax.swing.JLabel lbcSL;
    // End of variables declaration//GEN-END:variables
}
