/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Smartphone_sales_management.UI.Component.NhaCungCap;

import Smartphone_sales_management.BUS.QuanLyNhaCungCap_BUS;
import Smartphone_sales_management.DTO.Model_NhaCungCap;
import Smartphone_sales_management.UI.Event.NhaCungCap.EventNhaCC;
import Smartphone_sales_management.UI.Main.MainFrame;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author lehongthai
 */
public class TableNhaCC extends javax.swing.JPanel {
    JFrame frame;
 QuanLyNhaCungCap_BUS qlncc = new QuanLyNhaCungCap_BUS();
    DefaultTableModel model = new DefaultTableModel();
    TableNhaCC nhacc;
    EventNhaCC event;
    private MainContentNCC mainnhacc;
    private DefaultTableCellRenderer cellRenderer;
    /**
     * Creates new form TableNhaCC
     */
   

    public TableNhaCC(EventNhaCC nhacc,MainContentNCC mainnhacc) {
        
        initComponents();
        this.mainnhacc = mainnhacc;
        model.addColumn("STT");
        model.addColumn("Mã nhà cung cấp");        
        model.addColumn("Tên nhà cung cấp");
        model.addColumn("Số điện thoại");
        model.addColumn("Địa chỉ");
          jTable1.setOpaque(false);
         jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().getColumnModel().setColumnMargin(1);
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14) {
        });
        jTable1.setRowHeight(25);
        jTable1.getTableHeader().setForeground(Color.WHITE);
        jTable1.getTableHeader().setBackground(new Color(14, 14, 14));

        SetDefaultTable("");
        jTable1.setModel(model);
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(jTable1.getModel());
        jTable1.setRowSorter(sorter);  
              jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(1).setMinWidth(100);
        jTable1.getColumnModel().getColumn(2).setMinWidth(130);
        jTable1.getColumnModel().getColumn(3).setMinWidth(70);
        jTable1.getColumnModel().getColumn(4).setMinWidth(70);
         cellRenderer = new DefaultTableCellRenderer();
        cellRenderer.setHorizontalAlignment(JLabel.CENTER);
        jTable1.getColumnModel().getColumn(0).setCellRenderer(cellRenderer);
        jTable1.getColumnModel().getColumn(1).setCellRenderer(cellRenderer);
        jTable1.getColumnModel().getColumn(2).setCellRenderer(cellRenderer);
        jTable1.getColumnModel().getColumn(3).setCellRenderer(cellRenderer);
        jTable1.getColumnModel().getColumn(4).setCellRenderer(cellRenderer);
    }
   

        
  public void SetDefaultTable(String keyWord) {
        jTable1.removeAll();
        model.setRowCount(0);
        ArrayList dataList = new ArrayList();
        dataList = qlncc.getDanhSachSanPham(keyWord);
        for (int i = 0; i < dataList.size(); i++) {
            
           model.addRow((Vector<?>) dataList.get(i));
        }
        jScrollPane1.repaint();
    }
  
// public void addEventSanPham(EventNhaCC event) {
//        jTable1.addMouseListener(new MouseAdapter() {
//            @Override
//            public void mouseClicked(MouseEvent e) {
////                event.selectedIndex(jTable1.getSelectedRow());
//                   event.SelectedInxex((int) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
//                   System.out.println((int) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
//            }
//        ;
//    }
//
//    );
//    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setRowHeight(35);
        jTable1.setSelectionBackground(new java.awt.Color(255, 0, 51));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int index = jTable1.getSelectedRow();
        Model_NhaCungCap NhaCC = new Model_NhaCungCap();
	TableModel model =jTable1.getModel();

        String Mancc = model.getValueAt(index, 1).toString();
         String Tenncc = model.getValueAt(index, 2).toString();
         String sdt = model.getValueAt(index, 3).toString();
        String diachi = model.getValueAt(index, 4).toString();
        NhaCC.setMacc(Integer.parseInt(Mancc));
        NhaCC.setTenncc(Tenncc);
        NhaCC.setSDT(sdt);
        NhaCC.setDiaChi(diachi); 

        mainnhacc.truyendulieu(NhaCC);
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
