/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Smartphone_sales_management.UI.Swing.Menu;

import Smartphone_sales_management.UI.Component.BanHangComponent.*;
import Smartphone_sales_management.BUS.QuanLyBanHang_BUS;
import Smartphone_sales_management.UI.Event.BanHang.EventBanHang;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JScrollBar;
import javax.swing.border.LineBorder;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import static Smartphone_sales_management.UI.Component.BanHangComponent.TableDetailBH.selectedIndex;
import Smartphone_sales_management.UI.Component.KhachHanggComponent.KhachHangg;
import Smartphone_sales_management.UI.Component.NhaCungCap.MainContentNCC;
import Smartphone_sales_management.UI.Component.NhanVienComponent.NhanVienGUI;
import Smartphone_sales_management.UI.Main.MainFrame;
import java.awt.GridLayout;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author Vuong
 */
public class ConNguoi extends javax.swing.JPanel {

    /**
     * Creates new form TestPanel2
     */
    MainFrame frame;
    JPanel panel;
    public ConNguoi(MainFrame frame, JPanel panel) {

        initComponents();
        this.frame = frame;
        this.panel = panel;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelNhanVien = new ReactPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelKhachHang = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelNhaCungCap = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1030, 530));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        panelNhanVien.setBackground(new java.awt.Color(255, 255, 102));
        panelNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelNhanVienMouseClicked(evt);
            }
        });
        panelNhanVien.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                panelNhanVienPropertyChange(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Quản Lý Nhân Viên");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/Icon_NhanVien.png"))); // NOI18N

        javax.swing.GroupLayout panelNhanVienLayout = new javax.swing.GroupLayout(panelNhanVien);
        panelNhanVien.setLayout(panelNhanVienLayout);
        panelNhanVienLayout.setHorizontalGroup(
            panelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNhanVienLayout.createSequentialGroup()
                .addGroup(panelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNhanVienLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelNhanVienLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel2)))
                .addGap(82, 82, 82))
        );
        panelNhanVienLayout.setVerticalGroup(
            panelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNhanVienLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227))
        );

        jPanel1.add(panelNhanVien);

        panelKhachHang.setBackground(new java.awt.Color(0, 102, 102));
        panelKhachHang.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelKhachHangMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelKhachHangMouseMoved(evt);
            }
        });
        panelKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelKhachHangMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Quản Lý Khách Hàng");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/Icon_KhachHang.png"))); // NOI18N

        javax.swing.GroupLayout panelKhachHangLayout = new javax.swing.GroupLayout(panelKhachHang);
        panelKhachHang.setLayout(panelKhachHangLayout);
        panelKhachHangLayout.setHorizontalGroup(
            panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKhachHangLayout.createSequentialGroup()
                .addGroup(panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKhachHangLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel5))
                    .addGroup(panelKhachHangLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3)))
                .addGap(92, 92, 92))
        );
        panelKhachHangLayout.setVerticalGroup(
            panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKhachHangLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
        );

        jPanel1.add(panelKhachHang);

        panelNhaCungCap.setBackground(new java.awt.Color(204, 204, 255));
        panelNhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelNhaCungCapMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Quản Lý Nhà Cung Cấp");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/Icon_NhaCungCap.png"))); // NOI18N

        javax.swing.GroupLayout panelNhaCungCapLayout = new javax.swing.GroupLayout(panelNhaCungCap);
        panelNhaCungCap.setLayout(panelNhaCungCapLayout);
        panelNhaCungCapLayout.setHorizontalGroup(
            panelNhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNhaCungCapLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(49, 49, 49))
            .addGroup(panelNhaCungCapLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelNhaCungCapLayout.setVerticalGroup(
            panelNhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNhaCungCapLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(panelNhaCungCap);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        NhanVienGUI a = new NhanVienGUI();
        jPanel1.removeAll();
        a.setBounds(0, 0, jPanel1.getWidth(), jPanel1.getHeight());
        jPanel1.setLayout(new GridLayout());
        jPanel1.add(a);
        a.validate();
//                    pack();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void panelNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNhanVienMouseClicked

        NhanVienGUI a = new NhanVienGUI();
//KhuyenMaiGUI a = new KhuyenMaiGUI(MainFrame.this);
//              MainConTentBanHang a = new MainConTentBanHang(MainFrame.this);
//                    MainContentDonHang a = new MainContentDonHang(MainFrame.this);
//                    MainContentSanPham a = new MainContentSanPham(MainFrame.this);
//                    MainConTentBanHang a = new MainConTentBanHang(MainFrame.this);

        panel.removeAll();

        a.setBounds(0, 0, panel.getWidth(), panel.getHeight());
        panel.setLayout(new GridLayout());
        panel.add(a);
        a.validate();

        // TODO add your handling code here:
    }//GEN-LAST:event_panelNhanVienMouseClicked

    private void panelKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelKhachHangMouseClicked
        KhachHangg a = new KhachHangg();
        panel.removeAll();

        a.setBounds(0, 0, panel.getWidth(), panel.getHeight());
        panel.setLayout(new GridLayout());
        panel.add(a);
        a.validate();

        // TODO add your handling code here:
    }//GEN-LAST:event_panelKhachHangMouseClicked

    private void panelNhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNhaCungCapMouseClicked
        MainContentNCC a = new MainContentNCC(frame);
        panel.removeAll();

        a.setBounds(0, 0, panel.getWidth(), panel.getHeight());
        panel.setLayout(new GridLayout());
        panel.add(a);
        a.validate();

// TODO add your handling code here:
    }//GEN-LAST:event_panelNhaCungCapMouseClicked

    private void panelKhachHangMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelKhachHangMouseMoved
           
//      JPanel parent = (JPanel)evt.getSource();
//      parent.setBackground(Color.red);
//    parent.revalidate();
    }//GEN-LAST:event_panelKhachHangMouseMoved

    private void panelKhachHangMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelKhachHangMouseDragged
        
        
//   JPanel parent = (JPanel)evt.getSource();
//      parent.setBackground(Color.GRAY);
//    parent.validate();
// TODO add your handling code here:
    }//GEN-LAST:event_panelKhachHangMouseDragged

    private void panelNhanVienPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_panelNhanVienPropertyChange
      

        
// TODO add your handling code here:
    }//GEN-LAST:event_panelNhanVienPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelKhachHang;
    private javax.swing.JPanel panelNhaCungCap;
    private javax.swing.JPanel panelNhanVien;
    // End of variables declaration//GEN-END:variables

}
