/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Smartphone_sales_management.UI.Component.KhachHanggComponent2;
import Smartphone_sales_management.BUS.QuanLyKhachHang_BUS;
import Smartphone_sales_management.BUS.QuanLyNhanVien_BUS;
import Smartphone_sales_management.DTO.Model_NhanVien;
import Smartphone_sales_management.UI.Main.MainFrame;
import Smartphone_sales_management.UI.Model.Model_KhachHang;
import java.awt.Color;
import java.awt.Font;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.CellRendererPane;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.AbstractDocument;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.DefaultTableCellRenderer;


/**
 *
 * @author Hiep
 */
public class KhachHangg2 extends javax.swing.JPanel {

    private QuanLyKhachHang_BUS qlkh = new QuanLyKhachHang_BUS();
       DefaultTableModel model;
    private int stateForm;
   private DefaultTableCellRenderer cellRenderer;
   
    

    /**
     * Creates new form KhachHangg
     */
    public KhachHangg2() {
        initComponents();
        txtXoa.setEnabled(false);
        txtSua.setEnabled(false);
        txtMakh.setVisible(false);
        txtMakh.setVisible(false);
        txtma.setVisible(false);
         model = (DefaultTableModel) jTable1.getModel();
        model.addColumn("Mã Khách Hàng");        
         model.addColumn("Tên Khách Hàng");
         model.addColumn("CMND");
         model.addColumn("SĐT");
         model.addColumn("Địa Chỉ");        
         model.addColumn("Email");
         model.addColumn("Ngày tạo");
         model.addColumn("Điểm Số");
         
         jTable1.setOpaque(false);
        jTable1.getTableHeader().getColumnModel().setColumnMargin(1);
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 15) {
        });
        jTable1.setRowHeight(25);
        jTable1.getTableHeader().setForeground(Color.WHITE);
        jTable1.getTableHeader().setBackground(new Color(14, 14, 14));
        SetDefaultTable();
        jTable1.setModel(model);
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(jTable1.getModel());
        jTable1.setRowSorter(sorter);
        
        jTable1.setModel(model);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(120);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(130);
        jTable1.getColumnModel().getColumn(3).setMinWidth(80);
        jTable1.getColumnModel().getColumn(4).setMinWidth(80);
        jTable1.getColumnModel().getColumn(5).setMinWidth(180);
        jTable1.getColumnModel().getColumn(6).setMinWidth(80);
        jTable1.getColumnModel().getColumn(7).setMinWidth(80);
        

        cellRenderer = new DefaultTableCellRenderer();
        cellRenderer.setHorizontalAlignment(JLabel.CENTER);
        jTable1.getColumnModel().getColumn(0).setCellRenderer(cellRenderer);
        jTable1.getColumnModel().getColumn(1).setCellRenderer(cellRenderer);
        jTable1.getColumnModel().getColumn(2).setCellRenderer(cellRenderer);
        jTable1.getColumnModel().getColumn(3).setCellRenderer(cellRenderer);
        jTable1.getColumnModel().getColumn(4).setCellRenderer(cellRenderer);
        jTable1.getColumnModel().getColumn(5).setCellRenderer(cellRenderer);
        jTable1.getColumnModel().getColumn(6).setCellRenderer(cellRenderer);
        jTable1.getColumnModel().getColumn(7).setCellRenderer(cellRenderer);
        
             
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     public void SetDefaultTable() {
        jTable1.removeAll();
        model.setRowCount(0);
        ArrayList<Model_KhachHang> dataList = new ArrayList<Model_KhachHang>();
        dataList = qlkh.getDanhSachKhachHang();
        for (int i = 0; i < dataList.size(); i++) {
            
            model.addRow( dataList.get(i).toArrayString());
        }
        jScrollPane1.repaint();
    }
     public void showAll(ArrayList<Model_KhachHang> kh) {
        model.setRowCount(0);
        for (int i = 0; i < kh.size(); i++) {
            model.addRow(new String[]{
                Integer.toString(kh.get(i).getMakh()),
                kh.get(i).getTenkh(),
                kh.get(i).getCmnd(),
                kh.get(i).getSDT(),
                kh.get(i).getDiaChi(),
                kh.get(i).getEmail(),
                kh.get(i).getNgaytao(),
                Integer.toString(kh.get(i).getDiemso()),
               kh.get(i).getTrangThai(),
            });
        }
     }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TimKiem = new javax.swing.JLabel();
        txtTimkiem = new javax.swing.JTextField();
        txtTimMakh = new javax.swing.JRadioButton();
        txtTimcmnd = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtTimTenkh = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtma = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMakh = new javax.swing.JTextField();
        txtTenkh = new javax.swing.JTextField();
        txtCmnd = new javax.swing.JTextField();
        txtSodt = new javax.swing.JTextField();
        txtDiachi = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNgaytao = new javax.swing.JTextField();
        txtDiemso = new javax.swing.JTextField();
        txtAdd = new javax.swing.JButton();
        txtSua = new javax.swing.JButton();
        txtXoa = new javax.swing.JButton();
        txtLammoi = new javax.swing.JButton();
        txtTimSDT = new javax.swing.JRadioButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        TimKiem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/search.png"))); // NOI18N
        TimKiem.setText("Tìm Kiếm");
        TimKiem.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TimKiemAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        TimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TimKiemMouseClicked(evt);
            }
        });

        txtTimkiem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimkiemActionPerformed(evt);
            }
        });

        buttonGroup1.add(txtTimMakh);
        txtTimMakh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtTimMakh.setText("MaKh");

        buttonGroup1.add(txtTimcmnd);
        txtTimcmnd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtTimcmnd.setText("CMND");
        txtTimcmnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimcmndActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Thông Tin Khách Hàng");

        buttonGroup1.add(txtTimTenkh);
        txtTimTenkh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtTimTenkh.setText("Tenkh");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/Goback.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(txtTimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)
                        .addComponent(txtTimMakh)
                        .addGap(18, 18, 18)
                        .addComponent(txtTimTenkh)
                        .addGap(31, 31, 31)
                        .addComponent(txtTimcmnd))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimMakh)
                    .addComponent(txtTimcmnd)
                    .addComponent(TimKiem)
                    .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimTenkh)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(255, 0, 51));
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(0, 0, 0))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/boy.png"))); // NOI18N
        jLabel2.setText("Quản Lí Khách Hàng");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtma.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtma.setText("Mã Khách Hàng");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Tên Khách Hàng");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Cmnd");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("SĐT");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Địa chỉ");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Email");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Ngày tạo");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Điểm số");

        txtAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/plus.png"))); // NOI18N
        txtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddActionPerformed(evt);
            }
        });

        txtSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/gear.png"))); // NOI18N
        txtSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuaActionPerformed(evt);
            }
        });

        txtXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/Delete2.png"))); // NOI18N
        txtXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtXoaActionPerformed(evt);
            }
        });

        txtLammoi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtLammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/reset.png"))); // NOI18N
        txtLammoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLammoiMouseClicked(evt);
            }
        });
        txtLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLammoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtma, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSodt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNgaytao, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDiemso, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtTenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMakh, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCmnd, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSua, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLammoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtma)
                    .addComponent(txtMakh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCmnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSodt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgaytao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiemso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLammoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtSua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        buttonGroup1.add(txtTimSDT);
        txtTimSDT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtTimSDT.setText("SĐT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimSDT)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTimSDT)
                        .addGap(27, 27, 27)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void dulieu(Model_KhachHang KhachHang){
        
      txtMakh.setText(Integer.toString(KhachHang.getMakh()));
      txtTenkh.setText(KhachHang.getTenkh());
      if(KhachHang.getCmnd() == null) {
          txtCmnd.setText("");
      }
      else {
          txtCmnd.setText(KhachHang.getCmnd());
      }
//      txtCmnd.setText(KhachHang.getCmnd());
      txtSodt.setText(KhachHang.getSDT());
      txtDiachi.setText(KhachHang.getDiaChi());
      txtEmail.setText(KhachHang.getEmail());
      txtNgaytao.setText(KhachHang.getNgaytao());
      txtDiemso.setText(Integer.toString(KhachHang.getDiemso()));
    
    }

      
    private void txtLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLammoiActionPerformed

    }//GEN-LAST:event_txtLammoiActionPerformed

    private void txtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddActionPerformed
        txtMakh.setVisible(false);
        txtMakh.setVisible(false);
//        if(stateForm != 1) {
//			JOptionPane.showMessageDialog(jLabelThem, "Vui lòng nhấn nút làm mới để có thể thêm dữ liệu");
//			return;
//		}
        String Ten = txtTenkh.getText();
        String Cmnd = txtCmnd.getText();
        String SDT = txtSodt.getText();
        String diachi = txtDiachi.getText();
        String Email = txtEmail.getText();
        String Ngaytao = txtNgaytao.getText();
        String Diemso =txtDiemso.getText();
       String EMAIL_PATTERN = 
            "^[a-zA-Z][\\w-]+@([\\w]+[.]\\w+)$";
        Boolean flag= true;
        String SDT_Pattern = "^[0]\\d{9}$";
        String CMND_Pattern = "\\d+";
        
        if(Ten.length() == 0){
            JOptionPane.showMessageDialog(txtTenkh,"Bạn chưa nhập tên khách hàng");
            return;
        }
        if(Ten.length()> 50){
            JOptionPane.showMessageDialog(txtTenkh,"Bạn nhập sai thông tin khách hàng");
            return;
        }
        if(Pattern.matches(CMND_Pattern,Cmnd)!=true)
        {
                        JOptionPane.showMessageDialog(null, "Số chứng minh nhân dân/Căn cước công dân không đúng định dạng");
                        flag=false;
                        return;
                        
        }
        
         if(Pattern.matches(SDT_Pattern,SDT)!=true)
        {
                        JOptionPane.showMessageDialog(null, "Số điện thoại không đúng định dạng");
                        flag=false;
                        return;
        }
         if(diachi.length() == 0){
            JOptionPane.showMessageDialog(txtDiachi,"Bạn chưa nhập địa chỉ");
            return;
        }
        if(diachi.length()>= 50){
            JOptionPane.showMessageDialog(txtDiachi,"Bạn nhập sai thông tin địa chỉ");
            return;

        }
        if(Email.length()>= 50){
            JOptionPane.showMessageDialog(txtEmail, "Bạn chưa nhập Email");
            return;
        }
        if(Pattern.matches(EMAIL_PATTERN, Email)!=true)
        {
                        JOptionPane.showMessageDialog(null, "Email không đúng định dạng");
                        flag=false;
                        return;
        }
        
       if(Ngaytao.equals("")){
           JOptionPane.showMessageDialog(null, "Vui lòng nhập Ngày tạo");
            flag=false;
            return;
       }
       if(Diemso.equals("")){
           JOptionPane.showMessageDialog(null, "Vui lòng nhập Điểm số");
            flag=false;
            return;
    }
    if(flag==false)
    { 
        }
        else
        {
                    
        }
       
 
        QuanLyKhachHang_BUS qlkh = new QuanLyKhachHang_BUS();
        
        Model_KhachHang KhachHang = new Model_KhachHang();
        KhachHang.setTenkh(Ten);
        KhachHang.setCmnd(Cmnd);
        KhachHang.setSDT(SDT);
        KhachHang.setDiaChi(diachi);
        KhachHang.setEmail(Email);
        KhachHang.setNgaytao(Ngaytao);
        KhachHang.setDiemso(Integer.parseInt(Diemso));
        KhachHang.setTrangThai("T");
        
        qlkh.AddKhachHang(KhachHang);

        SetDefaultTable();
        txtTenkh.setText("");
        txtCmnd.setText("");
        txtSodt.setText("");
        txtDiachi.setText("");
        txtEmail.setText("");
        txtNgaytao.setText("");
        txtDiemso.setText("");

    }//GEN-LAST:event_txtAddActionPerformed

    private void txtSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuaActionPerformed
     
        String makh = txtMakh.getText();
        String Ten = txtTenkh.getText();
        String Cmnd = txtCmnd.getText();
        String SĐT = txtSodt.getText();
        String Diachi = txtDiachi.getText();
        String Email = txtEmail.getText();
        String Ngaytao = txtNgaytao.getText();
        String Diemso = txtDiemso.getText();
        
        String EMAIL_PATTERN = 
            "^[a-zA-Z][\\w-]+@([\\w]+[.]\\w+)$";
        Boolean flag= true;
        String SDT_Pattern = "^[0]\\d{9}$";
        String CMND_Pattern = "\\d+";
        
        if(Ten.length() == 0){
            JOptionPane.showMessageDialog(txtTenkh,"Bạn chưa nhập tên khách hàng");
            return;
        }
        if(Ten.length()> 50){
            JOptionPane.showMessageDialog(txtTenkh,"Bạn nhập sai thông tin khách hàng");
            return;
        }
        if(Pattern.matches(CMND_Pattern,Cmnd)!=true)
        {
                        JOptionPane.showMessageDialog(null, "Số chứng minh nhân dân/Căn cước công dân không đúng định dạng");
                        flag=false;
                        return;
                        
        }
        
         if(Pattern.matches(SDT_Pattern,SĐT)!=true)
        {
                        JOptionPane.showMessageDialog(null, "Số điện thoại không đúng định dạng");
                        flag=false;
                        return;
        }
         if(Diachi.length() == 0){
            JOptionPane.showMessageDialog(txtDiachi,"Bạn chưa nhập địa chỉ");
            return;
        }
        if(Diachi.length()>= 50){
            JOptionPane.showMessageDialog(txtDiachi,"Bạn nhập sai thông tin địa chỉ");
            return;

        }
        if(Email.length()>= 50){
            JOptionPane.showMessageDialog(txtEmail, "Bạn chưa nhập Email");
            return;
        }
        if(Pattern.matches(EMAIL_PATTERN, Email)!=true)
        {
                        JOptionPane.showMessageDialog(null, "Email không đúng định dạng");
                        flag=false;
                        return;
        }
        
       if(Ngaytao.equals("")){
           JOptionPane.showMessageDialog(null, "Vui lòng nhập Ngày tạo");
            flag=false;
            return;
       }
       if(Diemso.equals("")){
           JOptionPane.showMessageDialog(null, "Vui lòng nhập Điểm số");
            flag=false;
            return;
    }
    if(flag==false)
    { 
        }
        else
        {
                    
        }
       
       
     
    QuanLyKhachHang_BUS qlkh = new QuanLyKhachHang_BUS();

        Model_KhachHang KhachHang = new Model_KhachHang();
        KhachHang.setMakh(Integer.parseInt(makh));
        KhachHang.setTenkh(Ten);
        KhachHang.setCmnd(Cmnd);
        KhachHang.setSDT(SĐT);
        KhachHang.setDiaChi(Diachi);
        KhachHang.setEmail(Email);
        KhachHang.setNgaytao(Ngaytao);
        KhachHang.setDiemso(Integer.parseInt(Diemso));
        KhachHang.setTrangThai("T");
        
        
        qlkh.updateKhachHang(KhachHang);

        SetDefaultTable();
        txtTenkh.setText("");
        txtCmnd.setText("");
        txtSodt.setText("");
        txtDiachi.setText("");
        txtEmail.setText("");
        txtNgaytao.setText("");
        txtDiemso.setText("");
       
    }//GEN-LAST:event_txtSuaActionPerformed

    private void txtXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtXoaActionPerformed
      
         txtMakh.setEnabled(false);
        txtMakh.setEnabled(false);
        String makh = txtMakh.getText();
        QuanLyKhachHang_BUS qlkh = new QuanLyKhachHang_BUS();
        
        Model_KhachHang KhachHang = new Model_KhachHang();
        KhachHang.setMakh(Integer.parseInt(makh));
        KhachHang.setTrangThai("F");
            int a = JOptionPane.showConfirmDialog(null, "Bạn muốn xóa không ?","Xóa Khách Hàng", JOptionPane.YES_NO_OPTION);
        if(a==JOptionPane.YES_OPTION) {
           qlkh.deteleKhachHang(KhachHang);
        SetDefaultTable();
        
        txtTenkh.setText("");
        txtCmnd.setText("");
        txtSodt.setText("");
        txtDiachi.setText("");
        txtEmail.setText("");
        txtNgaytao.setText("");
        txtDiemso.setText("");
        txtNgaytao.setText("");
        
       
        
       
        }
    }//GEN-LAST:event_txtXoaActionPerformed

    private void txtTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimkiemActionPerformed
if (txtTimkiem.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin cần tìm kiếm", "THÔNG BÁO", JOptionPane.WARNING_MESSAGE);
            } else {
                if(txtTimMakh.isSelected() == false && txtTimMakh.isSelected()== false && txtTimTenkh.isSelected()== false && txtTimcmnd.isSelected()==false){
                 JOptionPane.showMessageDialog(this, "Vui lòng chọn trường hợp cần tìm", "THÔNG BÁO", JOptionPane.WARNING_MESSAGE);
                 return;
                 }
                if (txtTimMakh.isSelected()) {
                    ArrayList<Model_KhachHang> dskh = qlkh.timKiemTheoMaKh(txtTimkiem.getText());
                    showAll(dskh);
                }
                if (txtTimTenkh.isSelected()) {
                    ArrayList<Model_KhachHang> dskh = qlkh.timKiemTheoTenkh(txtTimkiem.getText());
                    showAll(dskh);
                }
                if (txtTimcmnd.isSelected()) {
                    ArrayList<Model_KhachHang> dskh = qlkh.timKiemTheoCmnd(txtTimkiem.getText());
                    showAll(dskh);
                }
            }

    
    }//GEN-LAST:event_txtTimkiemActionPerformed

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
    
    }//GEN-LAST:event_jTable1AncestorAdded

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      txtMakh.setEnabled(false);
        txtMakh.setEnabled(false);
        txtXoa.setEnabled(true);
        txtSua.setEnabled(true);
        txtAdd.setEnabled(false);
        int index = jTable1.getSelectedRow();
        Model_KhachHang KhachHang = new Model_KhachHang();
	TableModel model =jTable1.getModel();

        String Makh = model.getValueAt(index,0).toString();
        String Tenkh = model.getValueAt(index, 1).toString();
        String Cmnd = model.getValueAt(index, 2).toString();
        String SDT = model.getValueAt(index, 3).toString();
        String Diachi = model.getValueAt(index, 4).toString();
        String Email = model.getValueAt(index, 5).toString();
        String Ngaytao = model.getValueAt(index, 6).toString();
        String Diemso = model.getValueAt(index, 7).toString();
        KhachHang.setMakh(Integer.parseInt(Makh));
        KhachHang.setTenkh(Tenkh);
        KhachHang.setCmnd(Cmnd);
        KhachHang.setSDT(SDT);
        KhachHang.setDiaChi(Diachi);
        KhachHang.setEmail(Email);
        KhachHang.setNgaytao(Ngaytao);
        KhachHang.setDiemso(Integer.parseInt(Diemso));
        dulieu(KhachHang);
    }//GEN-LAST:event_jTable1MouseClicked

    private void TimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TimKiemMouseClicked
         if (txtTimkiem.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin cần tìm kiếm", "THÔNG BÁO", JOptionPane.WARNING_MESSAGE);
            } else {
                if(txtTimMakh.isSelected() == false && txtTimTenkh.isSelected()== false && txtTimcmnd.isSelected()== false && txtTimSDT.isSelected()==false){
                 JOptionPane.showMessageDialog(this, "Vui lòng chọn trường hợp cần tìm", "THÔNG BÁO", JOptionPane.WARNING_MESSAGE);
                 return;
                 }
                if (txtTimMakh.isSelected()) {
                    ArrayList<Model_KhachHang> dskh = qlkh.timKiemTheoMaKh(txtTimkiem.getText());
                    showAll(dskh);
                }
                if (txtTimTenkh.isSelected()) {
                    ArrayList<Model_KhachHang> dskh = qlkh.timKiemTheoTenkh(txtTimkiem.getText());
                    showAll(dskh);
                }
                if (txtTimcmnd.isSelected()) {
                    ArrayList<Model_KhachHang> dskh = qlkh.timKiemTheoCmnd(txtTimkiem.getText());
                    showAll(dskh);
                }
                if (txtTimSDT.isSelected()) {
                    ArrayList<Model_KhachHang> dskh = qlkh.timKiemTheoSĐT(txtTimkiem.getText());
                    showAll(dskh);
                }
        }
    }//GEN-LAST:event_TimKiemMouseClicked

    private void TimKiemAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TimKiemAncestorAdded
//        if (txtTimkiem.getText().equals("")) {
//                JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin cần tìm kiếm", "THÔNG BÁO", JOptionPane.WARNING_MESSAGE);
//            } else {
//                if(txtTimMakh.isSelected() == false && txtTimTenkh.isSelected()== false && txtTimcmnd.isSelected()== false ){
//                 JOptionPane.showMessageDialog(this, "Vui lòng chọn trường hợp cần tìm", "THÔNG BÁO", JOptionPane.WARNING_MESSAGE);
//                 return;
//                 }
//                if (txtTimMakh.isSelected()) {
//                    ArrayList<Model_KhachHang> dskh = qlkh.timKiemTheoMaKh(txtTimkiem.getText());
//                    showAll(dskh);
//                }
//                if (txtTimTenkh.isSelected()) {
//                    ArrayList<Model_KhachHang> dskh = qlkh.timKiemTheoTenkh(txtTimkiem.getText());
//                    showAll(dskh);
//                }
//                if (txtTimcmnd.isSelected()) {
//                    ArrayList<Model_KhachHang> dskh = qlkh.timKiemTheoCmnd(txtTimkiem.getText());
//                    showAll(dskh);
//                }
//        }
    }//GEN-LAST:event_TimKiemAncestorAdded

    private void txtTimcmndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimcmndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimcmndActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        txtTimkiem.setText("");
         SetDefaultTable();
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtLammoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLammoiMouseClicked
        stateForm = 1;
         txtMakh.setVisible(false);
        txtMakh.setVisible(false);
          txtXoa.setEnabled(false);
        txtSua.setEnabled(false);
        txtAdd.setEnabled(true);
        txtTenkh.setText("");
        txtCmnd.setText("");
        txtSodt.setText("");
        txtDiachi.setText("");
        txtEmail.setText("");
        txtNgaytao.setText("");
        txtDiemso.setText("");
    }//GEN-LAST:event_txtLammoiMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TimKiem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton txtAdd;
    private javax.swing.JTextField txtCmnd;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtDiemso;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JButton txtLammoi;
    private javax.swing.JTextField txtMakh;
    private javax.swing.JTextField txtNgaytao;
    private javax.swing.JTextField txtSodt;
    private javax.swing.JButton txtSua;
    private javax.swing.JTextField txtTenkh;
    private javax.swing.JRadioButton txtTimMakh;
    private javax.swing.JRadioButton txtTimSDT;
    private javax.swing.JRadioButton txtTimTenkh;
    private javax.swing.JRadioButton txtTimcmnd;
    private javax.swing.JTextField txtTimkiem;
    private javax.swing.JButton txtXoa;
    private javax.swing.JLabel txtma;
    // End of variables declaration//GEN-END:variables

   
  
}