/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Smartphone_sales_management.UI.Component.KhuyenMaiComponent;

import Smartphone_sales_management.BUS.QuanLyKhuyenMai_BUS;
import Smartphone_sales_management.UI.Main.MainFrame;
import Smartphone_sales_management.UI.Model.Model_ChiTietKM;
import Smartphone_sales_management.DTO.Model_KhuyenMai;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author lehongthai
 */
public class KhuyenMaiGUI extends javax.swing.JPanel {

    private QuanLyKhuyenMai_BUS qlkm = new QuanLyKhuyenMai_BUS();
    private DefaultTableModel modelKM;
    private DefaultTableModel modelCTKM;

    /**
     * Creates new form KhuyenMaiGUI
     */
    public KhuyenMaiGUI(MainFrame mainFrame) {
        initComponents();
        showCTKM();
        showKM();
    }

    private void showCTKM() {
        modelCTKM = (DefaultTableModel) jTable1.getModel();
        modelCTKM.addColumn("MaChiTietKM");
        modelCTKM.addColumn("MaSP");
        modelCTKM.addColumn("TenSP");

        modelCTKM.addColumn("MaKM");
        modelCTKM.addColumn("TrangThai");
        jTable1.getTableHeader().getColumnModel().setColumnMargin(1);
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 15) {
        });
        jTable1.setRowHeight(25);
        jTable1.getTableHeader().setForeground(Color.WHITE);
        jTable1.getTableHeader().setBackground(new Color(14, 14, 14));

        jTable1.setModel(modelCTKM);
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(jTable1.getModel());
        jTable1.setRowSorter(sorter);
        setDefaultTableModelCTKM();
    }

    private void showKM() {
        modelKM = (DefaultTableModel) jTable2.getModel();
        modelKM.addColumn("MaKM");
        modelKM.addColumn("TenKM");
        modelKM.addColumn("PhanTramKM");
        modelKM.addColumn("TrangThai");
        jTable2.getTableHeader().getColumnModel().setColumnMargin(1);
        jTable2.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 15) {
        });
        jTable2.setRowHeight(25);
        jTable2.getTableHeader().setForeground(Color.WHITE);
        jTable2.getTableHeader().setBackground(new Color(14, 14, 14));

        jTable2.setModel(modelKM);
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(jTable2.getModel());
        jTable2.setRowSorter(sorter);
        setDefaultTableModelKM();
    }

    public void setDefaultTableModelCTKM() {
        jTable1.removeAll();
        modelCTKM.setRowCount(0);
        ArrayList<Model_ChiTietKM> dataList = new ArrayList<Model_ChiTietKM>();
        dataList = qlkm.getDanhSachKMChiTiet();
        for (int i = 0; i < dataList.size(); i++) {
            modelCTKM.addRow(dataList.get(i).toArrayString());
        }
        jScrollChiTietKM.repaint();
    }

    public void setDefaultTableModelKM() {
        jTable2.removeAll();
        modelKM.setRowCount(0);
        ArrayList<Model_KhuyenMai> dataList = new ArrayList<Model_KhuyenMai>();
        dataList = qlkm.getDanhSachKhuyenMai();
        for (int i = 0; i < dataList.size(); i++) {
            modelKM.addRow(dataList.get(i).toArrayString());
        }
        jScrollKM.repaint();
    }

    public void truyendulieuKM() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanelChiTietKM = new javax.swing.JPanel();
        jScrollChiTietKM = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabelMaCTKM = new javax.swing.JLabel();
        jLabelCTMaSP = new javax.swing.JLabel();
        jLableCTMaKM = new javax.swing.JLabel();
        jTextMaCTKM = new javax.swing.JTextField();
        jTextCTMaSP = new javax.swing.JTextField();
        jTexCTMaKM = new javax.swing.JTextField();
        jBRefeshCTKM = new javax.swing.JButton();
        jBUpdateCTKM = new javax.swing.JButton();
        jBThemCTKM = new javax.swing.JButton();
        jBDeleteCTKM = new javax.swing.JButton();
        jPanelKM = new javax.swing.JPanel();
        jScrollKM = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBUpdateKM = new javax.swing.JButton();
        jBrefesh = new javax.swing.JButton();
        jBThemKM = new javax.swing.JButton();
        jBdeleteKM = new javax.swing.JButton();
        jTextPtkm = new javax.swing.JTextField();
        jTextMakm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextTenKm = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1030, 509));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(1045, 530));

        jPanelChiTietKM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jScrollChiTietKM.setPreferredSize(new java.awt.Dimension(402, 402));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollChiTietKM.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelMaCTKM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMaCTKM.setText("Mã CTKM");

        jLabelCTMaSP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCTMaSP.setText("MaSP");

        jLableCTMaKM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLableCTMaKM.setText("MaKM");

        jTextMaCTKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMaCTKMActionPerformed(evt);
            }
        });

        jTexCTMaKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexCTMaKMActionPerformed(evt);
            }
        });

        jBRefeshCTKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/Refresh.png"))); // NOI18N

        jBUpdateCTKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/DonHang.png"))); // NOI18N
        jBUpdateCTKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUpdateCTKMActionPerformed(evt);
            }
        });

        jBThemCTKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/Add.png"))); // NOI18N
        jBThemCTKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBThemCTKMActionPerformed(evt);
            }
        });

        jBDeleteCTKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/Delete.png"))); // NOI18N
        jBDeleteCTKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeleteCTKMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMaCTKM, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextMaCTKM, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBRefeshCTKM, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jBUpdateCTKM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCTMaSP)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextCTMaSP)
                        .addGap(46, 46, 46)
                        .addComponent(jLableCTMaKM)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jBThemCTKM, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBDeleteCTKM)
                    .addComponent(jTexCTMaKM, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCTMaSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelMaCTKM, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextMaCTKM)
                        .addComponent(jTextCTMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTexCTMaKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLableCTMaKM, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBDeleteCTKM, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBThemCTKM, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBRefeshCTKM, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBUpdateCTKM, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanelChiTietKMLayout = new javax.swing.GroupLayout(jPanelChiTietKM);
        jPanelChiTietKM.setLayout(jPanelChiTietKMLayout);
        jPanelChiTietKMLayout.setHorizontalGroup(
            jPanelChiTietKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollChiTietKM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelChiTietKMLayout.setVerticalGroup(
            jPanelChiTietKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChiTietKMLayout.createSequentialGroup()
                .addComponent(jScrollChiTietKM, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelKM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jScrollKM.setPreferredSize(new java.awt.Dimension(402, 402));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollKM.setViewportView(jTable2);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("MaKM");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("PhanTramKM");

        jBUpdateKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/DonHang.png"))); // NOI18N
        jBUpdateKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUpdateKMActionPerformed(evt);
            }
        });

        jBrefesh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/Refresh.png"))); // NOI18N
        jBrefesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrefeshActionPerformed(evt);
            }
        });

        jBThemKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/Add.png"))); // NOI18N
        jBThemKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBThemKMActionPerformed(evt);
            }
        });

        jBdeleteKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/Delete.png"))); // NOI18N
        jBdeleteKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdeleteKMActionPerformed(evt);
            }
        });

        jTextPtkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPtkmActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("TenKM");

        jTextTenKm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTenKmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jBrefesh, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextMakm, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextTenKm, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jBUpdateKM, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBThemKM)
                        .addGap(85, 85, 85)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBdeleteKM)
                    .addComponent(jTextPtkm, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextMakm, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextTenKm, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextPtkm, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBUpdateKM, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBrefesh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBThemKM, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBdeleteKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelKMLayout = new javax.swing.GroupLayout(jPanelKM);
        jPanelKM.setLayout(jPanelKMLayout);
        jPanelKMLayout.setHorizontalGroup(
            jPanelKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelKMLayout.setVerticalGroup(
            jPanelKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKMLayout.createSequentialGroup()
                .addComponent(jScrollKM, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "TÌM KIẾM CHI TIẾT KHUYẾN MÃI", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "TÌM KIẾM KHUYẾN MÃI", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelChiTietKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelChiTietKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        jPanel4.getAccessibleContext().setAccessibleName("Tìm Kiếm Chi Tiết KM\n");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextMaCTKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMaCTKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMaCTKMActionPerformed

    private void jTextTenKmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTenKmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTenKmActionPerformed

    private void jTexCTMaKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexCTMaKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexCTMaKMActionPerformed

    private void jTextPtkmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPtkmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPtkmActionPerformed

    private void jBThemCTKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBThemCTKMActionPerformed
        String Mactkm = jTextMaCTKM.getText();
        String masp = jTextCTMaSP.getText();
        String makm = jTexCTMaKM.getText();

        QuanLyKhuyenMai_BUS qlkm = new QuanLyKhuyenMai_BUS();
        Model_ChiTietKM ChiTietKM = new Model_ChiTietKM();
        ChiTietKM.setMachitietkhuyenmai(Integer.parseInt(Mactkm));
        ChiTietKM.setMaSP(Integer.parseInt(masp));
        ChiTietKM.setMaKM(Integer.parseInt(makm));
        ChiTietKM.setTrangThai("T");
        qlkm.insertChiTietKM(ChiTietKM);
        setDefaultTableModelCTKM();

        jTextMaCTKM.setText("");
        jTextCTMaSP.setText("");
        jTexCTMaKM.setText("");
    }//GEN-LAST:event_jBThemCTKMActionPerformed

    private void jBThemKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBThemKMActionPerformed
        String makm = jTextMakm.getText();
        String tenkm = jTextTenKm.getText();
        String phantramkm = jTextPtkm.getText();

        QuanLyKhuyenMai_BUS qlkm = new QuanLyKhuyenMai_BUS();
        Model_KhuyenMai KhuyenMai = new Model_KhuyenMai();

        KhuyenMai.setMakm(Integer.parseInt(makm));
        KhuyenMai.setTenkm(tenkm);
        KhuyenMai.setPhantramkm(Float.parseFloat(phantramkm));
        KhuyenMai.setTrangthai("T");

        qlkm.Addkhuyenmai(KhuyenMai);
        setDefaultTableModelKM();
        jTextMakm.setText("");
        jTextTenKm.setText("");
        jTextPtkm.setText("");
    }//GEN-LAST:event_jBThemKMActionPerformed

    private void jBdeleteKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdeleteKMActionPerformed
        String makm = jTextMakm.getText();
        if (makm.length() > 0) {
            qlkm.deleteKhuyenMai(Integer.parseInt(jTextMakm.getText()));
            setDefaultTableModelKM();
        }
        jTextMakm.setText("");
        jTextTenKm.setText("");
        jTextPtkm.setText("");
    }//GEN-LAST:event_jBdeleteKMActionPerformed

    private void jBUpdateKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUpdateKMActionPerformed
        String makm = jTextMakm.getText();
        String tenkm = jTextTenKm.getText();
        String ptkm = jTextPtkm.getText();

        QuanLyKhuyenMai_BUS qlkm = new QuanLyKhuyenMai_BUS();
        Model_KhuyenMai KhuyenMai = new Model_KhuyenMai();
        KhuyenMai.setMakm(Integer.parseInt(makm));
        KhuyenMai.setTenkm(tenkm);
        KhuyenMai.setPhantramkm(Float.parseFloat(ptkm));
        KhuyenMai.setTrangthai("T");

        qlkm.updateKhuyenMai(KhuyenMai);
        setDefaultTableModelKM();
        jTextMakm.setText("");
        jTextTenKm.setText("");
        jTextPtkm.setText("");
    }//GEN-LAST:event_jBUpdateKMActionPerformed

    private void jBDeleteCTKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeleteCTKMActionPerformed
        String machitietkm = jTexCTMaKM.getText();
        if (machitietkm.length() > 0) {
            qlkm.deleteChiTietKM(Integer.parseInt(jTexCTMaKM.getText()));
        }
        setDefaultTableModelCTKM();
        jTextMaCTKM.setText("");
        jTextCTMaSP.setText("");
        jTexCTMaKM.setText("");
    }//GEN-LAST:event_jBDeleteCTKMActionPerformed

    private void jBUpdateCTKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUpdateCTKMActionPerformed
        String mactkm = jTexCTMaKM.getText();
        String masp = jTextCTMaSP.getText();
        String makm = jTexCTMaKM.getText();

        QuanLyKhuyenMai_BUS qlkm = new QuanLyKhuyenMai_BUS();
        Model_ChiTietKM ChiTietKM = new Model_ChiTietKM();
        ChiTietKM.setMachitietkhuyenmai(Integer.parseInt(mactkm));
        ChiTietKM.setMaSP(Integer.parseInt(masp));
        ChiTietKM.setMaKM(Integer.parseInt(makm));
        ChiTietKM.setTrangThai("T");

        qlkm.updateChiTietKM(ChiTietKM);
        setDefaultTableModelCTKM();
        jTextMaCTKM.setText("");
        jTextCTMaSP.setText("");
        jTexCTMaKM.setText("");
    }//GEN-LAST:event_jBUpdateCTKMActionPerformed

    private void jBrefeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrefeshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBrefeshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDeleteCTKM;
    private javax.swing.JButton jBRefeshCTKM;
    private javax.swing.JButton jBThemCTKM;
    private javax.swing.JButton jBThemKM;
    private javax.swing.JButton jBUpdateCTKM;
    private javax.swing.JButton jBUpdateKM;
    private javax.swing.JButton jBdeleteKM;
    private javax.swing.JButton jBrefesh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCTMaSP;
    private javax.swing.JLabel jLabelMaCTKM;
    private javax.swing.JLabel jLableCTMaKM;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelChiTietKM;
    private javax.swing.JPanel jPanelKM;
    private javax.swing.JScrollPane jScrollChiTietKM;
    private javax.swing.JScrollPane jScrollKM;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTexCTMaKM;
    private javax.swing.JTextField jTextCTMaSP;
    private javax.swing.JTextField jTextMaCTKM;
    private javax.swing.JTextField jTextMakm;
    private javax.swing.JTextField jTextPtkm;
    private javax.swing.JTextField jTextTenKm;
    // End of variables declaration//GEN-END:variables
}
