/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Smartphone_sales_management.UI.Component.NhanVienComponent;
import Smartphone_sales_management.BUS.QuanLyNhanVien_BUS;
import Smartphone_sales_management.UI.Main.MainFrame;
import Smartphone_sales_management.UI.Model.Model_NhanVien;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author lehongthai
 */
public class NhanVienGUI extends javax.swing.JPanel {

       private QuanLyNhanVien_BUS qlnv = new QuanLyNhanVien_BUS();
       DefaultTableModel model;
        // = 1 la trang thai them nhan vien, 2 la thang trai chinh sua thong tin
        private int stateForm;
    
        
        
    public NhanVienGUI(MainFrame mainFrame) {
      
        initComponents();
        jLMaNV.setVisible(false);
        jtMaNV.setVisible(false);
        jButtonUpdate.setToolTipText("UPDATE NHÂN VIÊN");
        jButtonXoa.setToolTipText("DELETE NHÂN VIÊN");
        jbthemnv.setToolTipText("INSERT NHÂN VIÊN");
        jBrefesh.setToolTipText("REFRESH");
        model = (DefaultTableModel) jTable1.getModel();
        model.addColumn("MaNV");        
         model.addColumn("TenNV");
         model.addColumn("SoCCCD");
         model.addColumn("Tuoi");
         model.addColumn("DiaChi");        
         model.addColumn("ChucDanh");
         model.addColumn("TrangThai");
         jTable1.setOpaque(false);
        jTable1.getTableHeader().getColumnModel().setColumnMargin(1);
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 15) {
        });
        jTable1.setRowHeight(25);
        jTable1.getTableHeader().setForeground(Color.WHITE);
        jTable1.getTableHeader().setBackground(new Color(14, 14, 14));
        SetDefaultTable();
        jTable1.setModel(model);
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(jTable1.getModel());
        jTable1.setRowSorter(sorter);
    
    }
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      public void SetDefaultTable() {
        jTable1.removeAll();
        model.setRowCount(0);
        ArrayList<Model_NhanVien> dataList = new ArrayList<Model_NhanVien>();
        dataList = qlnv.getDanhSachNhanVien();
        for (int i = 0; i < dataList.size(); i++) {
            
            model.addRow( dataList.get(i).toArrayString());
        }
        jScrollPane1.repaint();
    }

       public void showAll(ArrayList<Model_NhanVien> nv) {
        model.setRowCount(0);
        for (int i = 0; i < nv.size(); i++) {
            model.addRow(new String[]{
                Integer.toString(nv.get(i).getMaNV()),
                nv.get(i).getTenNV(),
                Integer.toString(nv.get (i).getSoCCCD()),
                Integer.toString(nv.get(i).getTuoi()),
                nv.get(i).getDiaChi(),
                nv.get(i).getChucDanh(),
               nv.get(i).getTrangThai(),
            });
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jtTen = new javax.swing.JTextField();
        jlTenNhanVien = new javax.swing.JLabel();
        jbTuoi = new javax.swing.JLabel();
        jtTuoi = new javax.swing.JTextField();
        jbSocccd = new javax.swing.JLabel();
        jtcccd = new javax.swing.JTextField();
        jbChucDanh = new javax.swing.JLabel();
        jtChucdanh = new javax.swing.JTextField();
        jbthemnv = new javax.swing.JButton();
        jLabelDiaChi = new javax.swing.JLabel();
        jTextDiaChi = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jtMaNV = new javax.swing.JTextField();
        jLMaNV = new javax.swing.JLabel();
        jBrefesh = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtTuKhoa = new javax.swing.JTextField();
        rdbMaNV = new javax.swing.JRadioButton();
        rdbTenNV = new javax.swing.JRadioButton();
        rdbDiaChi = new javax.swing.JRadioButton();
        rdbSocccd = new javax.swing.JRadioButton();
        rdbTuoi = new javax.swing.JRadioButton();
        btnResetSearch = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTuoiBD = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTuoiKT = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JLabel();
        rdbThongThuong = new javax.swing.JRadioButton();
        rdbNangCao = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        rdbTuoiNC = new javax.swing.JRadioButton();
        rdbchucdanh = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        rdbMaNC = new javax.swing.JRadioButton();
        txtMaBD = new javax.swing.JTextField();
        txtMaKT = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLALL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1045, 530));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTenActionPerformed(evt);
            }
        });

        jlTenNhanVien.setText("Tên nhân viên");

        jbTuoi.setText("Tuổi");

        jtTuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTuoiActionPerformed(evt);
            }
        });

        jbSocccd.setText("Số CCCD");

        jbChucDanh.setText("Chức danh");

        jtChucdanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtChucdanhActionPerformed(evt);
            }
        });

        jbthemnv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/NhanVien.png"))); // NOI18N
        jbthemnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbthemnvActionPerformed(evt);
            }
        });

        jLabelDiaChi.setText("Điạ Chỉ");

        jTextDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDiaChiActionPerformed(evt);
            }
        });

        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/boy.png"))); // NOI18N
        jButtonUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonUpdateMouseClicked(evt);
            }
        });
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/Delete.png"))); // NOI18N
        jButtonXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonXoaMouseClicked(evt);
            }
        });

        jtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtMaNVActionPerformed(evt);
            }
        });

        jLMaNV.setText("MaNV");

        jBrefesh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/Refresh.png"))); // NOI18N
        jBrefesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrefeshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(80, Short.MAX_VALUE)
                        .addComponent(jBrefesh)
                        .addGap(29, 29, 29)
                        .addComponent(jButtonUpdate)
                        .addGap(30, 30, 30)
                        .addComponent(jbthemnv)
                        .addGap(28, 28, 28)
                        .addComponent(jButtonXoa)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelDiaChi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbSocccd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbTuoi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlTenNhanVien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(jLMaNV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbChucDanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtTen)
                            .addComponent(jtTuoi)
                            .addComponent(jtcccd)
                            .addComponent(jTextDiaChi)
                            .addComponent(jtChucdanh, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtMaNV))))
                .addGap(11, 11, 11))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtTen, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jlTenNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jbTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtcccd, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jbSocccd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabelDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbChucDanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtChucdanh, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbthemnv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jBrefesh, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonXoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        jPanel4.setBackground(new java.awt.Color(233, 213, 218));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "TÌM KIẾM", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Baloo 2", 1, 18))); // NOI18N
        jPanel4.setToolTipText("");
        jPanel4.setVerifyInputWhenFocusTarget(false);

        jLabel10.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        jLabel10.setText("Nhập từ khóa");

        rdbMaNV.setBackground(new java.awt.Color(233, 213, 218));
        buttonGroup2.add(rdbMaNV);
        rdbMaNV.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rdbMaNV.setText("Mã NV");

        rdbTenNV.setBackground(new java.awt.Color(233, 213, 218));
        buttonGroup2.add(rdbTenNV);
        rdbTenNV.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rdbTenNV.setText("Tên NV");

        rdbDiaChi.setBackground(new java.awt.Color(233, 213, 218));
        buttonGroup2.add(rdbDiaChi);
        rdbDiaChi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rdbDiaChi.setText("Địa chỉ");
        rdbDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbDiaChiActionPerformed(evt);
            }
        });

        rdbSocccd.setBackground(new java.awt.Color(233, 213, 218));
        buttonGroup2.add(rdbSocccd);
        rdbSocccd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rdbSocccd.setText("Số CCCD");
        rdbSocccd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbSocccdActionPerformed(evt);
            }
        });

        rdbTuoi.setBackground(new java.awt.Color(233, 213, 218));
        buttonGroup2.add(rdbTuoi);
        rdbTuoi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rdbTuoi.setText("Tuổi");

        btnResetSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetSearchMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("đến");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Tìm kiếm tuổi từ:");

        btnTimKiem.setFont(new java.awt.Font("Baloo 2", 1, 16)); // NOI18N
        btnTimKiem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/search.png"))); // NOI18N
        btnTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKiemMouseClicked(evt);
            }
        });

        rdbThongThuong.setBackground(new java.awt.Color(233, 213, 218));
        buttonGroup1.add(rdbThongThuong);

        rdbNangCao.setBackground(new java.awt.Color(233, 213, 218));
        buttonGroup1.add(rdbNangCao);

        jLabel14.setFont(new java.awt.Font("Baloo 2 ExtraBold", 3, 16)); // NOI18N
        jLabel14.setText("Tìm kiếm nâng cao");

        rdbTuoiNC.setBackground(new java.awt.Color(233, 213, 218));
        buttonGroup3.add(rdbTuoiNC);

        rdbchucdanh.setBackground(new java.awt.Color(233, 213, 218));
        buttonGroup2.add(rdbchucdanh);
        rdbchucdanh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rdbchucdanh.setText("Chức danh");
        rdbchucdanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbchucdanhActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Tìm kiếm mã NV  từ:");

        rdbMaNC.setBackground(new java.awt.Color(233, 213, 218));
        buttonGroup3.add(rdbMaNC);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("đến");

        jLALL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/Goback.png"))); // NOI18N
        jLALL.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLALLAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jLALL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLALLMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdbNangCao)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(rdbTuoiNC)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtTuoiBD, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtTuoiKT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                            .addComponent(rdbMaNC)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel15)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtMaBD, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtMaKT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(rdbDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdbTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdbchucdanh)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdbThongThuong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(26, 26, 26)
                                .addComponent(txtTuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(rdbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdbTenNV)
                                .addGap(12, 12, 12)
                                .addComponent(rdbSocccd, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLALL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(btnResetSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnResetSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(txtTuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rdbThongThuong))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbMaNV)
                            .addComponent(rdbTenNV)
                            .addComponent(rdbSocccd)))
                    .addComponent(jLALL))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbTuoi)
                            .addComponent(rdbDiaChi)
                            .addComponent(rdbchucdanh))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(rdbNangCao)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txtMaBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(txtMaKT, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rdbMaNC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbTuoiNC)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txtTuoiKT, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtTuoiBD, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NHÂN VIÊN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel1)
                        .addGap(80, 236, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, Short.MAX_VALUE))
                .addGap(3, 3, 3))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void jtTuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTuoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTuoiActionPerformed

    private void jtChucdanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtChucdanhActionPerformed
        jtChucdanh.setVisible(false);
    }//GEN-LAST:event_jtChucdanhActionPerformed

    private void jbthemnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbthemnvActionPerformed
        jLMaNV.setVisible(false);
        jtMaNV.setVisible(false);
        if(stateForm !=1) {
		JOptionPane.showMessageDialog(jbthemnv, "Vui lòng bấm vào nút tạo mới nhân viên để có thể thêm dữ liệu");
		return;
		}
        String ten = jtTen.getText();
        String tuoi = jtTuoi.getText();
        String Socccd = jtcccd.getText();
        String diachi = jTextDiaChi.getText();
        String chucdanh = jtChucdanh.getText();

        Pattern p = Pattern.compile("^[0-9]+$");
        
        if(ten.length() == 0){
            JOptionPane.showMessageDialog(jtTen,"Bạn chưa nhập tên nhân viên");
            return;
        }
        if(ten.length()> 50){
            JOptionPane.showMessageDialog(jtTen,"Bạn nhập sai thông tin nhân viên");
            return;
        }
        if( Integer.parseInt(tuoi) < 18){
            JOptionPane.showMessageDialog(jtTuoi,"Bạn cần nhập lại tuổi");
            return;
        }
        if( Integer.parseInt(tuoi) > 70){
            JOptionPane.showMessageDialog(jtTuoi,"Số tuổi cần nhập lại tuổi");
            return;
        }
        
        if(Socccd.length() < 0){
            JOptionPane.showMessageDialog(jtcccd,"Bạn cần nhập số CCCD");
            return;
        }
        if(qlnv.ExistsNhanVien(Integer.parseInt(Socccd))){
            JOptionPane.showMessageDialog(jtcccd, "Số căn cước đã tồn tại");
            return;
        }
        if(Socccd.length()>13){
            JOptionPane.showMessageDialog(jtcccd,"Số cccd không được vượt quá 12 số ");
            return;
        }
        if(diachi.length() == 0){
            JOptionPane.showMessageDialog(jTextDiaChi,"Bạn chưa nhập địa chỉ");
            return;
        }
        if(diachi.length()>= 50){
            JOptionPane.showMessageDialog(jTextDiaChi,"Bạn nhập sai thông tin diachi");
            return;

        }
        if(chucdanh.length() == 0){
            JOptionPane.showMessageDialog(jtChucdanh,"Bạn chưa nhập chức danh");
            return;
        }
        if(chucdanh.length()>= 50){
            JOptionPane.showMessageDialog(jtChucdanh,"Bạn nhập sai thông tin chuc danh");
            return;
        }
        QuanLyNhanVien_BUS qlnv = new QuanLyNhanVien_BUS();

        Model_NhanVien NhanVien = new Model_NhanVien();
        NhanVien.setTenNV(ten);
        if(p.matcher(tuoi).find()){
        NhanVien.setTuoi(Integer.parseInt(tuoi));
        }else{
            JOptionPane.showMessageDialog(jtTuoi,"Bạn nhập sai kiểu dữ liệu của tuổi");
                return;
        }
        if(p.matcher(Socccd).find()){
        NhanVien.setSoCCCD(Integer.parseInt(Socccd));
        }else{
            JOptionPane.showMessageDialog(jtTuoi,"Bạn nhập sai kiểu dữ liệu của SoCCCD");
               return;
        }
        NhanVien.setDiaChi(diachi);
        NhanVien.setChucDanh(chucdanh);
        NhanVien.setTrangThai("T");
        NhanVien.setMaNV(qlnv.getSoTTMANV());
        
        qlnv.AddNhanVien(NhanVien);

        SetDefaultTable();
        jtTen.setText("");
        jtTuoi.setText("");
        jtcccd.setText("");
        jTextDiaChi.setText("");
        jtChucdanh.setText("");
    }//GEN-LAST:event_jbthemnvActionPerformed

    private void jTextDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDiaChiActionPerformed

    private void jtTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTenActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        
    }//GEN-LAST:event_jButtonUpdateActionPerformed
    public void truyendulieu(Model_NhanVien NhanVien){
        stateForm =2;
      jtMaNV.setText(Integer.toString(NhanVien.getMaNV()));
      jtTen.setText(NhanVien.getTenNV());
      jtTuoi.setText(Integer.toString(NhanVien.getTuoi()));
      jtcccd.setText(Integer.toString(NhanVien.getSoCCCD()));
      jTextDiaChi.setText(NhanVien.getDiaChi());
      jtChucdanh.setText(NhanVien.getChucDanh());
      jtTen.repaint();
 }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        jLMaNV.setVisible(true);
        jtMaNV.setVisible(true);   
        int index = jTable1.getSelectedRow();
            Model_NhanVien NhanVien = new Model_NhanVien();
	TableModel model =jTable1.getModel();

        String Manv = model.getValueAt(index,0).toString();
         String Ten = model.getValueAt(index, 1).toString();
         String SoCCCD = model.getValueAt(index, 2).toString();
        String Tuoi = model.getValueAt(index, 3).toString();
        String Diachi = model.getValueAt(index, 4).toString();
        String Chucdanh = model.getValueAt(index, 5).toString();
        NhanVien.setMaNV(Integer.parseInt(Manv));
        NhanVien.setTenNV(Ten);
        NhanVien.setTuoi(Integer.parseInt(Tuoi));
        NhanVien.setSoCCCD(Integer.parseInt(Tuoi));
        NhanVien.setDiaChi(Diachi);
        NhanVien.setChucDanh(Chucdanh);       
        truyendulieu(NhanVien);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonXoaMouseClicked
      if(stateForm != 2) {
			JOptionPane.showMessageDialog(jButtonXoa, "Vui lòng chọn 1 dòng dữ liệu bên bảng nhân viên để xóa");
			return;
		}
        String manv = jtMaNV.getText();
      if(manv.length()>0){
       qlnv.deleteNhanVien(Integer.parseInt(jtMaNV.getText()));
       SetDefaultTable();
      }
      if(manv.length() == 0){
        JOptionPane.showMessageDialog(jlTenNhanVien, "Bạn cần phải nhập mã nhân viên cần xóa");
    }
     jtMaNV.setText("");
        jtTen.setText("");
        jtTuoi.setText("");
        jtcccd.setText("");
        jTextDiaChi.setText("");
        jtChucdanh.setText("");
        
        
    }//GEN-LAST:event_jButtonXoaMouseClicked

    private void jtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtMaNVActionPerformed

    }//GEN-LAST:event_jtMaNVActionPerformed

    private void jButtonUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpdateMouseClicked
       if(stateForm != 2) {
			JOptionPane.showMessageDialog(jButtonXoa, "Vui lòng chọn 1 dòng dữ liệu bên bảng nhân viên để có thể tiến hành chỉnh sửa thông tin dữ liêu");
			return;
		}
        String manv = jtMaNV.getText();
        String ten = jtTen.getText();
        String tuoi = jtTuoi.getText();
        String Socccd = jtcccd.getText();
        String diachi = jTextDiaChi.getText();
        String chucdanh = jtChucdanh.getText();
    
        if(ten.length() == 0){
            JOptionPane.showMessageDialog(jtTen,"Bạn chưa nhập tên nhân viên");
            return;
        }
        if(ten.length()> 50){
            JOptionPane.showMessageDialog(jtTen,"Bạn nhập sai thông tin nhân viên");
            return;
        }
        if( Integer.parseInt(tuoi) < 18){
            JOptionPane.showMessageDialog(jtTuoi,"Bạn cần nhập lại tuổi");
            return;
        }
        if( Integer.parseInt(tuoi) > 70){
            JOptionPane.showMessageDialog(jtTuoi,"Số tuổi cần nhập lại tuổi");
            return;
        }
        if(Socccd.length() < 0){
            JOptionPane.showMessageDialog(jtcccd,"Bạn cần nhập số CCCD");
            return;
        }
        if(Socccd.length()>13){
            JOptionPane.showMessageDialog(jtcccd,"Số cccd không được vượt quá 12 số ");
            return;
        }
        if(diachi.length() == 0){
            JOptionPane.showMessageDialog(jTextDiaChi,"Bạn chưa nhập địa chỉ");
            return;
        }
        if(diachi.length()>= 50){
            JOptionPane.showMessageDialog(jTextDiaChi,"Bạn nhập sai thông tin diachi");

        }
        if(chucdanh.length() == 0){
            JOptionPane.showMessageDialog(jtChucdanh,"Bạn chưa nhập chức danh");
        }
        if(chucdanh.length()>= 50){
            JOptionPane.showMessageDialog(jtChucdanh,"Bạn nhập sai thông tin chuc danh");

        }
        QuanLyNhanVien_BUS qlnv = new QuanLyNhanVien_BUS();
        Model_NhanVien NhanVien = new Model_NhanVien();
        NhanVien.setMaNV(Integer.parseInt(manv));
        NhanVien.setTenNV(ten);
        Pattern p = Pattern.compile("^[0-9]+$");
        if(p.matcher(tuoi).find()){
        NhanVien.setTuoi(Integer.parseInt(tuoi));
        }else{
            JOptionPane.showMessageDialog(jtTuoi,"Bạn nhập sai kiểu dữ liệu của tuổi");
            return;
        }
        if(p.matcher(Socccd).find()){
        NhanVien.setSoCCCD(Integer.parseInt(Socccd));
        }else{
            JOptionPane.showMessageDialog(jtTuoi,"Bạn nhập sai kiểu dữ liệu của SoCCCD");
             return;
        }
        NhanVien.setDiaChi(diachi);
        NhanVien.setChucDanh(chucdanh); 
        
       qlnv.updateNhanVien(NhanVien);
       
       SetDefaultTable();
        jtMaNV.setText("");
        jtTen.setText("");
        jtTuoi.setText("");
        jtcccd.setText("");
        jTextDiaChi.setText("");
        jtChucdanh.setText("");
        
        
    }//GEN-LAST:event_jButtonUpdateMouseClicked

    private void jBrefeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrefeshActionPerformed
        stateForm = 1;
        jLMaNV.setVisible(false);
        jtMaNV.setVisible(false);
        jtTen.setText("");
        jtTuoi.setText("");
        jtcccd.setText("");
        jTextDiaChi.setText("");
        jtChucdanh.setText("");
    }//GEN-LAST:event_jBrefeshActionPerformed

    private void btnResetSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetSearchMouseClicked
//      
    }//GEN-LAST:event_btnResetSearchMouseClicked

    private void btnTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemMouseClicked

        if (rdbThongThuong.isSelected()) {
            if (txtTuKhoa.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin cần tìm kiếm", "THÔNG BÁO", JOptionPane.WARNING_MESSAGE);
            } else {
                if (rdbMaNV.isSelected()) {
                    ArrayList<Model_NhanVien> dsnv = qlnv.timKiemTheoMaNV(txtTuKhoa.getText());
                    showAll(dsnv);
                }
                if (rdbTenNV.isSelected()) {
                    ArrayList<Model_NhanVien> dsnv = qlnv.timKiemTheoTen(txtTuKhoa.getText());
                    showAll(dsnv);
                }
                if (rdbTuoi.isSelected()) {
                    ArrayList<Model_NhanVien> dsnv = qlnv.timKiemTheoTuoi(txtTuKhoa.getText());
                    showAll(dsnv);
                }
                if (rdbSocccd.isSelected()) {
                    ArrayList<Model_NhanVien> dsnv = qlnv.timKiemTheocccd(txtTuKhoa.getText());
                    showAll(dsnv);
                }
                if (rdbDiaChi.isSelected()) {
                    ArrayList<Model_NhanVien> dsnv = qlnv.timKiemTheoDiaChi(txtTuKhoa.getText());
                    showAll(dsnv);
                }
                if (rdbchucdanh.isSelected()) {
                    ArrayList<Model_NhanVien> dsnv = qlnv.timKiemTheoChucDanh(txtTuKhoa.getText());
                    showAll(dsnv);
                }
            }
      }
        
         if (rdbNangCao.isSelected()) {
                 if (rdbMaNC.isSelected()) {
                    if (txtMaBD.getText().equals("") && txtMaKT.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Không được bỏ trống thông tin", "Thông báo", JOptionPane.WARNING_MESSAGE);

                } else {
                        Pattern p = Pattern.compile("^[0-9]+$");
                     if (p.matcher(txtMaBD.getText()).find() && p.matcher(txtMaKT.getText()).find()) {
                    ArrayList<Model_NhanVien> dsnv = qlnv.timKiemMaNVNangCao(txtMaBD.getText(), txtMaKT.getText());
                    showAll(dsnv);
                    }else{
                    JOptionPane.showMessageDialog(null, "Bạn phải nhập vào kiểu Int cho MaNV", "Thông báo", JOptionPane.WARNING_MESSAGE);

                     }
                }
            }
   
            if (rdbTuoiNC.isSelected()) {
                if (txtTuoiBD.getText().equals("") && txtTuoiKT.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Không được  bỏ trống thông tin", "Thông báo", JOptionPane.WARNING_MESSAGE);
//                
                   
                } else {
                    Pattern p = Pattern.compile("^[0-9]+$");
                    if (p.matcher(txtTuoiBD.getText()).find() && p.matcher(txtTuoiKT.getText()).find()) {
                        ArrayList<Model_NhanVien> dsnv = qlnv.timKiemTuoiNangCao(txtTuoiBD.getText(), txtTuoiKT.getText());
                        showAll(dsnv);
                    }else{
                        JOptionPane.showMessageDialog(null, "Bạn phải nhập vào kiểu Int cho Tuổi", "Thông báo", JOptionPane.WARNING_MESSAGE);

                    }
                }
            }
        }  
    }//GEN-LAST:event_btnTimKiemMouseClicked

    private void rdbchucdanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbchucdanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbchucdanhActionPerformed

    private void rdbSocccdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbSocccdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbSocccdActionPerformed

    private void jLALLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLALLMouseClicked
        txtTuKhoa.setText("");
        txtTuoiBD.setText("");
        txtTuoiKT.setText("");
        txtMaBD.setText("");
        txtMaKT.setText("");
        SetDefaultTable();
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
    }//GEN-LAST:event_jLALLMouseClicked

    private void rdbDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbDiaChiActionPerformed

    private void jLALLAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLALLAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLALLAncestorAdded
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnResetSearch;
    private javax.swing.JLabel btnTimKiem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jBrefesh;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JLabel jLALL;
    private javax.swing.JLabel jLMaNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabelDiaChi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextDiaChi;
    private javax.swing.JLabel jbChucDanh;
    private javax.swing.JLabel jbSocccd;
    private javax.swing.JLabel jbTuoi;
    private javax.swing.JButton jbthemnv;
    private javax.swing.JLabel jlTenNhanVien;
    private javax.swing.JTextField jtChucdanh;
    private javax.swing.JTextField jtMaNV;
    private javax.swing.JTextField jtTen;
    private javax.swing.JTextField jtTuoi;
    private javax.swing.JTextField jtcccd;
    private javax.swing.JRadioButton rdbDiaChi;
    private javax.swing.JRadioButton rdbMaNC;
    private javax.swing.JRadioButton rdbMaNV;
    private javax.swing.JRadioButton rdbNangCao;
    private javax.swing.JRadioButton rdbSocccd;
    private javax.swing.JRadioButton rdbTenNV;
    private javax.swing.JRadioButton rdbThongThuong;
    private javax.swing.JRadioButton rdbTuoi;
    private javax.swing.JRadioButton rdbTuoiNC;
    private javax.swing.JRadioButton rdbchucdanh;
    private javax.swing.JTextField txtMaBD;
    private javax.swing.JTextField txtMaKT;
    private javax.swing.JTextField txtTuKhoa;
    private javax.swing.JTextField txtTuoiBD;
    private javax.swing.JTextField txtTuoiKT;
    // End of variables declaration//GEN-END:variables
}

