/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Smartphone_sales_management.UI.Component.NhanVienComponent;
import Smartphone_sales_management.BUS.QuanLyNhanVien_BUS;
import Smartphone_sales_management.DTO.Model_NhanVien;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author lehongthai
 */
public class NhanVienGUI extends javax.swing.JPanel {

       private QuanLyNhanVien_BUS qlnv = new QuanLyNhanVien_BUS();
       DefaultTableModel model;
        // = 1 la trang thai them nhan vien, 2 la thang trai chinh sua thong tin
        private int stateForm;
        private DefaultTableCellRenderer cellRenderer;
        
        
    public NhanVienGUI() {
      
        initComponents();
//        jLabelXoa.setEnabled(false);
//        jLabelChinhSua.setEnabled(false);
        jLMaNV.setVisible(false);
        jtMaNV.setVisible(false);
        model = (DefaultTableModel) jTable1.getModel();
        model.addColumn("Mã nhân viên");        
         model.addColumn("Tên nhân viên");
         model.addColumn("Số căn cước công dân");
         model.addColumn("Tuổi");
         model.addColumn("Địa chỉ");        
         model.addColumn("Chức danh");
//         model.addColumn("TrangThai");
         jTable1.setOpaque(false);
         jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().getColumnModel().setColumnMargin(1);
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 15) {
        });
        jTable1.setRowHeight(25);
        jTable1.getTableHeader().setForeground(Color.WHITE);
        jTable1.getTableHeader().setBackground(new Color(14, 14, 14));
        SetDefaultTable();
    
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(1).setMinWidth(115);
        jTable1.getColumnModel().getColumn(2).setMinWidth(155);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(4).setMinWidth(145);
        jTable1.getColumnModel().getColumn(5).setMinWidth(95);

        cellRenderer = new DefaultTableCellRenderer();
        cellRenderer.setHorizontalAlignment(JLabel.CENTER);
        jTable1.getColumnModel().getColumn(0).setCellRenderer(cellRenderer);
        jTable1.getColumnModel().getColumn(1).setCellRenderer(cellRenderer);
        jTable1.getColumnModel().getColumn(2).setCellRenderer(cellRenderer);
        jTable1.getColumnModel().getColumn(3).setCellRenderer(cellRenderer);
        jTable1.getColumnModel().getColumn(4).setCellRenderer(cellRenderer);
        jTable1.getColumnModel().getColumn(5).setCellRenderer(cellRenderer);
    }
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      public void SetDefaultTable() {
        jTable1.removeAll();
        model.setRowCount(0);
        ArrayList<Model_NhanVien> dataList = new ArrayList<Model_NhanVien>();
        dataList = qlnv.getDanhSachNhanVien();
        for (int i = 0; i < dataList.size(); i++) {
            
            model.addRow( dataList.get(i).toArrayString());
        }
        jScrollPane1.repaint();
    }

       public void showAll(ArrayList<Model_NhanVien> nv) {
        model.setRowCount(0);
        for (int i = 0; i < nv.size(); i++) {
            model.addRow(new String[]{
                Integer.toString(nv.get(i).getMaNV()),
                nv.get(i).getTenNV(),
                Integer.toString(nv.get (i).getSoCCCD()),
                Integer.toString(nv.get(i).getTuoi()),
                nv.get(i).getDiaChi(),
                nv.get(i).getChucDanh(),
               nv.get(i).getTrangThai(),
            });
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jtTen = new javax.swing.JTextField();
        jlTenNhanVien = new javax.swing.JLabel();
        jbTuoi = new javax.swing.JLabel();
        jtTuoi = new javax.swing.JTextField();
        jbSocccd = new javax.swing.JLabel();
        jtcccd = new javax.swing.JTextField();
        jbChucDanh = new javax.swing.JLabel();
        jtChucdanh = new javax.swing.JTextField();
        jLabelDiaChi = new javax.swing.JLabel();
        jTextDiaChi = new javax.swing.JTextField();
        jtMaNV = new javax.swing.JTextField();
        jLMaNV = new javax.swing.JLabel();
        jLabelLamMoi = new javax.swing.JLabel();
        jLabelThem = new javax.swing.JLabel();
        jLabelChinhSua = new javax.swing.JLabel();
        jLabelXoa = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtTuKhoa = new javax.swing.JTextField();
        rdbMaNV = new javax.swing.JRadioButton();
        rdbTenNV = new javax.swing.JRadioButton();
        rdbDiaChi = new javax.swing.JRadioButton();
        rdbSocccd = new javax.swing.JRadioButton();
        rdbTuoi = new javax.swing.JRadioButton();
        btnResetSearch = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTuoiBD = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTuoiKT = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JLabel();
        rdbThongThuong = new javax.swing.JRadioButton();
        rdbNangCao = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        rdbTuoiNC = new javax.swing.JRadioButton();
        rdbchucdanh = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        rdbMaNC = new javax.swing.JRadioButton();
        txtMaBD = new javax.swing.JTextField();
        txtMaKT = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1045, 530));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTenActionPerformed(evt);
            }
        });

        jlTenNhanVien.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jlTenNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTenNhanVien.setText("Tên nhân viên");

        jbTuoi.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jbTuoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbTuoi.setText("Tuổi");

        jtTuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTuoiActionPerformed(evt);
            }
        });

        jbSocccd.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jbSocccd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbSocccd.setText("Số CCCD");

        jbChucDanh.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jbChucDanh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbChucDanh.setText("Chức danh");

        jtChucdanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtChucdanhActionPerformed(evt);
            }
        });

        jLabelDiaChi.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabelDiaChi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDiaChi.setText("Điạ Chỉ");

        jTextDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDiaChiActionPerformed(evt);
            }
        });

        jtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtMaNVActionPerformed(evt);
            }
        });

        jLMaNV.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLMaNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMaNV.setText("MaNV");

        jLabelLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/reset.png"))); // NOI18N
        jLabelLamMoi.setText("Làm mới");
        jLabelLamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLamMoiMouseClicked(evt);
            }
        });

        jLabelThem.setBackground(new java.awt.Color(0, 0, 0));
        jLabelThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/plus.png"))); // NOI18N
        jLabelThem.setText("Thêm");
        jLabelThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelThemMouseClicked(evt);
            }
        });

        jLabelChinhSua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelChinhSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/gear.png"))); // NOI18N
        jLabelChinhSua.setText("Chỉnh sửa");
        jLabelChinhSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelChinhSuaMouseClicked(evt);
            }
        });

        jLabelXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/remove.png"))); // NOI18N
        jLabelXoa.setText("Xóa");
        jLabelXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelXoaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelDiaChi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbSocccd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbTuoi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlTenNhanVien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLMaNV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbChucDanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextDiaChi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtcccd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtTuoi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtTen, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtMaNV, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtChucdanh))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelThem, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelChinhSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelLamMoi)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelXoa)
                        .addGap(16, 16, 16))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtTen, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jlTenNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jbTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtcccd, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jbSocccd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabelDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbChucDanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtChucdanh, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelXoa)
                    .addComponent(jLabelLamMoi)
                    .addComponent(jLabelChinhSua)
                    .addComponent(jLabelThem))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "TÌM KIẾM", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Baloo 2", 1, 18))); // NOI18N
        jPanel4.setToolTipText("");
        jPanel4.setVerifyInputWhenFocusTarget(false);

        jLabel10.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        jLabel10.setText("Nhập từ khóa");

        rdbMaNV.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rdbMaNV);
        rdbMaNV.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rdbMaNV.setText("Mã NV");

        rdbTenNV.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rdbTenNV);
        rdbTenNV.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rdbTenNV.setText("Tên NV");

        rdbDiaChi.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rdbDiaChi);
        rdbDiaChi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rdbDiaChi.setText("Địa chỉ");
        rdbDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbDiaChiActionPerformed(evt);
            }
        });

        rdbSocccd.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rdbSocccd);
        rdbSocccd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rdbSocccd.setText("Số CCCD");
        rdbSocccd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbSocccdActionPerformed(evt);
            }
        });

        rdbTuoi.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rdbTuoi);
        rdbTuoi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rdbTuoi.setText("Tuổi");

        btnResetSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetSearchMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("đến");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Tìm kiếm tuổi từ:");

        btnTimKiem.setFont(new java.awt.Font("Baloo 2", 1, 16)); // NOI18N
        btnTimKiem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/search.png"))); // NOI18N
        btnTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKiemMouseClicked(evt);
            }
        });

        rdbThongThuong.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdbThongThuong);

        rdbNangCao.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdbNangCao);

        jLabel14.setFont(new java.awt.Font("Baloo 2 ExtraBold", 3, 16)); // NOI18N
        jLabel14.setText("Tìm kiếm nâng cao");

        rdbTuoiNC.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(rdbTuoiNC);

        rdbchucdanh.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rdbchucdanh);
        rdbchucdanh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rdbchucdanh.setText("Chức danh");
        rdbchucdanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbchucdanhActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Tìm kiếm mã NV  từ:");

        rdbMaNC.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(rdbMaNC);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("đến");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone_sales_management/UI/Icon/Goback.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdbNangCao)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(rdbMaNC)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel15))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(rdbTuoiNC)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel13)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(txtTuoiBD, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtTuoiKT, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(txtMaBD, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtMaKT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(rdbDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdbTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdbchucdanh)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(7, Short.MAX_VALUE)
                        .addComponent(rdbThongThuong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(26, 26, 26)
                                .addComponent(txtTuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(rdbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdbTenNV)
                                .addGap(12, 12, 12)
                                .addComponent(rdbSocccd, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)))
                .addComponent(btnResetSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 4, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnResetSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtTuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rdbThongThuong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbMaNV)
                    .addComponent(rdbTenNV)
                    .addComponent(rdbSocccd)
                    .addComponent(jLabel2))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbTuoi)
                            .addComponent(rdbDiaChi)
                            .addComponent(rdbchucdanh))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(rdbNangCao)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txtMaBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(txtMaKT, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rdbMaNC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbTuoiNC)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txtTuoiKT, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtTuoiBD, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NHÂN VIÊN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(3, 3, 3))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(406, 406, 406)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void jtTuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTuoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTuoiActionPerformed

    private void jtChucdanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtChucdanhActionPerformed
        jtChucdanh.setVisible(false);
    }//GEN-LAST:event_jtChucdanhActionPerformed

    private void jTextDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDiaChiActionPerformed

    private void jtTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTenActionPerformed
    public void truyendulieu(Model_NhanVien NhanVien){
        stateForm =2;
      jtMaNV.setText(Integer.toString(NhanVien.getMaNV()));
      jtTen.setText(NhanVien.getTenNV());
      jtTuoi.setText(Integer.toString(NhanVien.getTuoi()));
      jtcccd.setText(Integer.toString(NhanVien.getSoCCCD()));
      jTextDiaChi.setText(NhanVien.getDiaChi());
      jtChucdanh.setText(NhanVien.getChucDanh());
    
 }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        jLMaNV.setEnabled(false);
        jtMaNV.setEnabled(false);
//        jLabelXoa.setEnabled(true);
//        jLabelChinhSua.setEnabled(true);
//        jLabelThem.setEnabled(false);
        int index = jTable1.getSelectedRow();
        Model_NhanVien NhanVien = new Model_NhanVien();
	TableModel model =jTable1.getModel();

        String Manv = model.getValueAt(index,0).toString();
         String Ten = model.getValueAt(index, 1).toString();
         String SoCCCD = model.getValueAt(index, 2).toString();
        String Tuoi = model.getValueAt(index, 3).toString();
        String Diachi = model.getValueAt(index, 4).toString();
        String Chucdanh = model.getValueAt(index, 5).toString();
        NhanVien.setMaNV(Integer.parseInt(Manv));
        NhanVien.setTenNV(Ten);
        NhanVien.setSoCCCD(Integer.parseInt(SoCCCD));
        NhanVien.setTuoi(Integer.parseInt(Tuoi));
        NhanVien.setDiaChi(Diachi);
        NhanVien.setChucDanh(Chucdanh);       
        truyendulieu(NhanVien);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtMaNVActionPerformed

    }//GEN-LAST:event_jtMaNVActionPerformed

    private void btnResetSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetSearchMouseClicked
//      
    }//GEN-LAST:event_btnResetSearchMouseClicked

    private void btnTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemMouseClicked
if(rdbThongThuong.isSelected() == false  && rdbNangCao.isSelected() == false){
                    JOptionPane.showMessageDialog(this, "Vui lòng chọn trường hợp cần tìm", "THÔNG BÁO", JOptionPane.WARNING_MESSAGE);
                    return;
                    }
        if (rdbThongThuong.isSelected()) {
            if (txtTuKhoa.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin cần tìm kiếm", "THÔNG BÁO", JOptionPane.WARNING_MESSAGE);
            } else {
                if(rdbMaNV.isSelected() == false && rdbTenNV.isSelected()== false && rdbTuoi.isSelected()== false && rdbSocccd.isSelected()==false && rdbDiaChi.isSelected()==false && rdbchucdanh.isSelected()==false){
                 JOptionPane.showMessageDialog(this, "Vui lòng chọn trường hợp cần tìm", "THÔNG BÁO", JOptionPane.WARNING_MESSAGE);
                 return;
                 }
                if (rdbMaNV.isSelected()) {
                    ArrayList<Model_NhanVien> dsnv = qlnv.timKiemTheoMaNV(txtTuKhoa.getText());
                    showAll(dsnv);
                }
                if (rdbTenNV.isSelected()) {
                    ArrayList<Model_NhanVien> dsnv = qlnv.timKiemTheoTen(txtTuKhoa.getText());
                    showAll(dsnv);
                }
                if (rdbTuoi.isSelected()) {
                    ArrayList<Model_NhanVien> dsnv = qlnv.timKiemTheoTuoi(txtTuKhoa.getText());
                    showAll(dsnv);
                }
                if (rdbSocccd.isSelected()) {
                    ArrayList<Model_NhanVien> dsnv = qlnv.timKiemTheocccd(txtTuKhoa.getText());
                    showAll(dsnv);
                }
                if (rdbDiaChi.isSelected()) {
                    ArrayList<Model_NhanVien> dsnv = qlnv.timKiemTheoDiaChi(txtTuKhoa.getText());
                    showAll(dsnv);
                }
                if (rdbchucdanh.isSelected()) {
                    ArrayList<Model_NhanVien> dsnv = qlnv.timKiemTheoChucDanh(txtTuKhoa.getText());
                    showAll(dsnv);
                }
            }
      }
        
         if (rdbNangCao.isSelected()) {
              if(rdbMaNC.isSelected() == false && rdbTuoiNC.isSelected()==false)
              {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn tìm theo mã hoặc tìm theo tuổi", "Thông báo", JOptionPane.WARNING_MESSAGE);

              }
                 if (rdbMaNC.isSelected()) {
                    if (txtMaBD.getText().equals("") && txtMaKT.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Không được bỏ trống thông tin", "Thông báo", JOptionPane.WARNING_MESSAGE);

                } else {
                        Pattern p = Pattern.compile("^[0-9]+$");
                     if (p.matcher(txtMaBD.getText()).find() && p.matcher(txtMaKT.getText()).find()) {
                    ArrayList<Model_NhanVien> dsnv = qlnv.timKiemMaNVNangCao(txtMaBD.getText(), txtMaKT.getText());
                    showAll(dsnv);
                    }else{
                    JOptionPane.showMessageDialog(null, "Bạn phải nhập vào kiểu Int cho MaNV", "Thông báo", JOptionPane.WARNING_MESSAGE);

                     }
                }
            }
   
            if (rdbTuoiNC.isSelected()) {
                if (txtTuoiBD.getText().equals("") && txtTuoiKT.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Không được  bỏ trống thông tin", "Thông báo", JOptionPane.WARNING_MESSAGE);
//                
                   
                } else {
                    Pattern p = Pattern.compile("^[0-9]+$");
                    if (p.matcher(txtTuoiBD.getText()).find() && p.matcher(txtTuoiKT.getText()).find()) {
                        ArrayList<Model_NhanVien> dsnv = qlnv.timKiemTuoiNangCao(txtTuoiBD.getText(), txtTuoiKT.getText());
                        showAll(dsnv);
                    }else{
                        JOptionPane.showMessageDialog(null, "Bạn phải nhập vào kiểu Int cho Tuổi", "Thông báo", JOptionPane.WARNING_MESSAGE);

                    }
                }
            }
        }  
    }//GEN-LAST:event_btnTimKiemMouseClicked

    private void rdbchucdanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbchucdanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbchucdanhActionPerformed

    private void rdbSocccdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbSocccdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbSocccdActionPerformed

    private void rdbDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbDiaChiActionPerformed

    private void jLabelLamMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLamMoiMouseClicked
             stateForm = 1;
         jLMaNV.setVisible(false);
        jtMaNV.setVisible(false);
//          jLabelXoa.setEnabled(false);
//        jLabelChinhSua.setEnabled(false);
//        jLabelThem.setEnabled(true);
        jtTen.setText("");
        jtTuoi.setText("");
        jtcccd.setText("");
        jTextDiaChi.setText("");
        jtChucdanh.setText("");
    }//GEN-LAST:event_jLabelLamMoiMouseClicked

    private void jLabelThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelThemMouseClicked
    jLMaNV.setVisible(false);
        jtMaNV.setVisible(false);
        if(stateForm != 1) {
			JOptionPane.showMessageDialog(jLabelThem, "Vui lòng nhấn nút làm mới để có thể thêm dữ liệu");
			return;
		}

        String ten = jtTen.getText();
        String tuoi = jtTuoi.getText();
        String Socccd = jtcccd.getText();
        String diachi = jTextDiaChi.getText();
        String chucdanh = jtChucdanh.getText();
        String TUOI_Pattern = "\\d+";
        String CMND_Pattern = "\\d+";
        Pattern p = Pattern.compile("[0-9]");
//                if (p.matcher(jtTen.getText()).find()){
//            JOptionPane.showMessageDialog(jtTen,"Bạn  nhập sai định dạng tên nhân viên");
//            return;
//        }
             if (p.matcher(jtChucdanh.getText()).find()){
            JOptionPane.showMessageDialog(jtTen,"Bạn  nhập sai định dạng chức danh ");
            return;
        }
        if(ten.length() == 0){
            JOptionPane.showMessageDialog(jtTen,"Bạn chưa nhập tên nhân viên");
            return;
        }
        if(ten.length()> 50){
            JOptionPane.showMessageDialog(jtTen,"Bạn nhập sai thông tin nhân viên");
            return;
        }
        if (p.matcher(jtTen.getText()).find()){
            
        }
         if(Pattern.matches(TUOI_Pattern,tuoi)!=true)
        {
                        JOptionPane.showMessageDialog(null, "Số tuổi không đúng định dạng");
                        return;
        }
        if( Integer.parseInt(tuoi) < 18){
            JOptionPane.showMessageDialog(jtTuoi,"Số tuổi chưa đủ tuổi lao động ");
            return;
        }
        if( Integer.parseInt(tuoi) > 70){
            JOptionPane.showMessageDialog(jtTuoi,"Ngoài độ tuổi lao động");
            return;
        }
        if(Socccd.length()>13){
            JOptionPane.showMessageDialog(jtcccd,"Số cccd không được vượt quá 12 số ");
            return;
        }
         if(Pattern.matches(CMND_Pattern,Socccd)!=true)
        {
                        JOptionPane.showMessageDialog(null, "Số chứng minh nhân dân/Căn cước công dân không đúng định dạng");
                        return;
        }
        if(qlnv.ExistsNhanVien(Integer.parseInt(Socccd))){
            JOptionPane.showMessageDialog(jtcccd, "Số căn cước đã tồn tại");
            return;
        }
       
        if(diachi.length() == 0){
            JOptionPane.showMessageDialog(jTextDiaChi,"Bạn chưa nhập địa chỉ");
            return;
        }
        if(diachi.length()>= 50){
            JOptionPane.showMessageDialog(jTextDiaChi,"Bạn nhập sai thông tin diachi");
            return;

        }
        if(chucdanh.length() == 0){
            JOptionPane.showMessageDialog(jtChucdanh,"Bạn chưa nhập chức danh");
            return;
        }
        if(chucdanh.length()>= 50){
            JOptionPane.showMessageDialog(jtChucdanh,"Bạn nhập sai thông tin chuc danh");
            return;
        }
        QuanLyNhanVien_BUS qlnv = new QuanLyNhanVien_BUS();
        
        Model_NhanVien NhanVien = new Model_NhanVien();
        NhanVien.setTenNV(ten);
        NhanVien.setTuoi(Integer.parseInt(tuoi));
        NhanVien.setSoCCCD(Integer.parseInt(Socccd));
        NhanVien.setDiaChi(diachi);
        NhanVien.setChucDanh(chucdanh);
        NhanVien.setTrangThai("T");
          int a = JOptionPane.showConfirmDialog(null, "Bạn muốn thêm không ?","Thêm Nhân Viên", JOptionPane.YES_NO_OPTION);
        if(a==JOptionPane.YES_OPTION) {
           qlnv.AddNhanVien(NhanVien);

        SetDefaultTable();
         jtTen.setText("");
        jtTuoi.setText("");
        jtcccd.setText("");
        jTextDiaChi.setText("");
        jtChucdanh.setText("");
        } 

       
    }//GEN-LAST:event_jLabelThemMouseClicked

    private void jLabelChinhSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelChinhSuaMouseClicked
        if(stateForm != 2) {
			JOptionPane.showMessageDialog(jLabelChinhSua, "Vui lòng chọn 1 dòng dữ liệu bên bảng nhân viên để có thể tiến hành chỉnh sửa thông tin dữ liêu");
			return;
		}
        String manv = jtMaNV.getText();
          String ten = jtTen.getText();
        String tuoi = jtTuoi.getText();
        String Socccd = jtcccd.getText();
        String diachi = jTextDiaChi.getText();
        String chucdanh = jtChucdanh.getText();
        String TUOI_Pattern = "\\d+";
        String CMND_Pattern = "\\d+";
        Pattern p = Pattern.compile("[0-9]");
                if (p.matcher(jtTen.getText()).find()){
            JOptionPane.showMessageDialog(jtTen,"Bạn  nhập sai định dạng tên nhân viên");
            return;
        }
             if (p.matcher(jtChucdanh.getText()).find()){
            JOptionPane.showMessageDialog(jtTen,"Bạn  nhập sai định dạng chức danh ");
            return;
        }
        
        if(ten.length() == 0){
            JOptionPane.showMessageDialog(jtTen,"Bạn chưa nhập tên nhân viên");
            return;
        }
        if(ten.length()> 50){
            JOptionPane.showMessageDialog(jtTen,"Bạn nhập sai thông tin nhân viên");
            return;
        }
         if(Pattern.matches(TUOI_Pattern,tuoi)!=true)
        {
                        JOptionPane.showMessageDialog(null, "Số tuổi không đúng định dạng");
                        return;
        }
        if( Integer.parseInt(tuoi) < 18){
            JOptionPane.showMessageDialog(jtTuoi,"Số tuổi chưa đủ tuổi lao động");
            return;
        }
        if( Integer.parseInt(tuoi) > 70){
            JOptionPane.showMessageDialog(jtTuoi,"Ngoài độ tuổi lao động ");
            return;
        }
        if(Socccd.length()>13){
            JOptionPane.showMessageDialog(jtcccd,"Số cccd không được vượt quá 12 số ");
            return;
        }
         if(Pattern.matches(CMND_Pattern,Socccd)!=true)
        {
                        JOptionPane.showMessageDialog(null, "Số chứng minh nhân dân/Căn cước công dân không đúng định dạng");
                        return;
        }
       
        if(diachi.length() == 0){
            JOptionPane.showMessageDialog(jTextDiaChi,"Bạn chưa nhập địa chỉ");
            return;
        }
        if(diachi.length()>= 50){
            JOptionPane.showMessageDialog(jTextDiaChi,"Bạn nhập sai thông tin địa chỉ");
            return;

        }
        if(chucdanh.length() == 0){
            JOptionPane.showMessageDialog(jtChucdanh,"Bạn chưa nhập chức danh");
            return;
        }
        if(chucdanh.length()>= 50){
            JOptionPane.showMessageDialog(jtChucdanh,"Bạn nhập sai thông tin chuc danh");
            return;
        }
        QuanLyNhanVien_BUS qlnv = new QuanLyNhanVien_BUS();
        
        Model_NhanVien NhanVien = new Model_NhanVien();
        NhanVien.setMaNV(Integer.parseInt(manv));
        NhanVien.setTenNV(ten);
        NhanVien.setTuoi(Integer.parseInt(tuoi));
        NhanVien.setSoCCCD(Integer.parseInt(Socccd));
        NhanVien.setDiaChi(diachi);
        NhanVien.setChucDanh(chucdanh);  
              int a = JOptionPane.showConfirmDialog(null, "Bạn muốn chỉnh sửa thông tin không ?","Chỉnh sửa thông tin Nhân Viên", JOptionPane.YES_NO_OPTION);
        if(a==JOptionPane.YES_OPTION) {
           qlnv.updateNhanVien(NhanVien);

        SetDefaultTable();
         jtTen.setText("");
        jtTuoi.setText("");
        jtcccd.setText("");
        jTextDiaChi.setText("");
        jtChucdanh.setText("");
        } 
    }//GEN-LAST:event_jLabelChinhSuaMouseClicked

    private void jLabelXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelXoaMouseClicked
        jLMaNV.setEnabled(false);
        jtMaNV.setEnabled(false);
        if(stateForm != 2) {
			JOptionPane.showMessageDialog(jLabelXoa, "Vui lòng chọn 1 dòng dữ liệu bên bảng nhân viên để xóa");
			return;
		}
        String manv = jtMaNV.getText();
        QuanLyNhanVien_BUS qlnv = new QuanLyNhanVien_BUS();
        
        Model_NhanVien nhanvien = new Model_NhanVien();
        nhanvien.setMaNV(Integer.parseInt(manv));
        nhanvien.setTrangThai("F");
            int a = JOptionPane.showConfirmDialog(null, "Bạn muốn xóa không ?","Xóa Nhân Viên", JOptionPane.YES_NO_OPTION);
        if(a==JOptionPane.YES_OPTION) {
           qlnv.deleteNhanVien(nhanvien);
        SetDefaultTable();
        jtTen.setText("");
        jtTuoi.setText("");
        jtcccd.setText("");
        jTextDiaChi.setText("");
        jtChucdanh.setText("");
        jtTen.setText("");
        jtTuoi.setText("");
        jtcccd.setText("");
        jTextDiaChi.setText("");
        }
    }//GEN-LAST:event_jLabelXoaMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        txtTuKhoa.setText("");
        txtTuoiBD.setText("");
        txtTuoiKT.setText("");
        txtMaBD.setText("");
        txtMaKT.setText("");
        SetDefaultTable();
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
    }//GEN-LAST:event_jLabel2MouseClicked
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnResetSearch;
    private javax.swing.JLabel btnTimKiem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLMaNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelChinhSua;
    private javax.swing.JLabel jLabelDiaChi;
    private javax.swing.JLabel jLabelLamMoi;
    private javax.swing.JLabel jLabelThem;
    private javax.swing.JLabel jLabelXoa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextDiaChi;
    private javax.swing.JLabel jbChucDanh;
    private javax.swing.JLabel jbSocccd;
    private javax.swing.JLabel jbTuoi;
    private javax.swing.JLabel jlTenNhanVien;
    private javax.swing.JTextField jtChucdanh;
    private javax.swing.JTextField jtMaNV;
    private javax.swing.JTextField jtTen;
    private javax.swing.JTextField jtTuoi;
    private javax.swing.JTextField jtcccd;
    private javax.swing.JRadioButton rdbDiaChi;
    private javax.swing.JRadioButton rdbMaNC;
    private javax.swing.JRadioButton rdbMaNV;
    private javax.swing.JRadioButton rdbNangCao;
    private javax.swing.JRadioButton rdbSocccd;
    private javax.swing.JRadioButton rdbTenNV;
    private javax.swing.JRadioButton rdbThongThuong;
    private javax.swing.JRadioButton rdbTuoi;
    private javax.swing.JRadioButton rdbTuoiNC;
    private javax.swing.JRadioButton rdbchucdanh;
    private javax.swing.JTextField txtMaBD;
    private javax.swing.JTextField txtMaKT;
    private javax.swing.JTextField txtTuKhoa;
    private javax.swing.JTextField txtTuoiBD;
    private javax.swing.JTextField txtTuoiKT;
    // End of variables declaration//GEN-END:variables
}

